/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AccessToken
 */

public class AccessToken {
  @SerializedName("id")
  private Long id;

  @SerializedName("name")
  private String name;

  @SerializedName("scopes")
  private List<String> scopes;

  @SerializedName("sha1")
  private String sha1;

  @SerializedName("token_last_eight")
  private String tokenLastEight;

  public AccessToken id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public AccessToken name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AccessToken scopes(List<String> scopes) {
    this.scopes = scopes;
    return this;
  }

  public AccessToken addScopesItem(String scopesItem) {
    if (this.scopes == null) {
      this.scopes = new ArrayList<String>();
    }
    this.scopes.add(scopesItem);
    return this;
  }

  /**
   * Get scopes
   *
   * @return scopes
   **/
  @Schema(description = "")
  public List<String> getScopes() {
    return scopes;
  }

  public void setScopes(List<String> scopes) {
    this.scopes = scopes;
  }

  public AccessToken sha1(String sha1) {
    this.sha1 = sha1;
    return this;
  }

  /**
   * Get sha1
   *
   * @return sha1
   **/
  @Schema(description = "")
  public String getSha1() {
    return sha1;
  }

  public void setSha1(String sha1) {
    this.sha1 = sha1;
  }

  public AccessToken tokenLastEight(String tokenLastEight) {
    this.tokenLastEight = tokenLastEight;
    return this;
  }

  /**
   * Get tokenLastEight
   *
   * @return tokenLastEight
   **/
  @Schema(description = "")
  public String getTokenLastEight() {
    return tokenLastEight;
  }

  public void setTokenLastEight(String tokenLastEight) {
    this.tokenLastEight = tokenLastEight;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessToken accessToken = (AccessToken) o;
    return Objects.equals(this.id, accessToken.id) &&
           Objects.equals(this.name, accessToken.name) &&
           Objects.equals(this.scopes, accessToken.scopes) &&
           Objects.equals(this.sha1, accessToken.sha1) &&
           Objects.equals(this.tokenLastEight, accessToken.tokenLastEight);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, scopes, sha1, tokenLastEight);
  }


  @Override
  public String toString() {

    String sb = "class AccessToken {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    scopes: " + toIndentedString(scopes) + "\n" +
                "    sha1: " + toIndentedString(sha1) + "\n" +
                "    tokenLastEight: " + toIndentedString(tokenLastEight) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
