/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ActionTaskResponse returns a ActionTask
 */
@Schema(description = "ActionTaskResponse returns a ActionTask")
public class ActionTaskResponse {
  @SerializedName("total_count")
  private Long totalCount;

  @SerializedName("workflow_runs")
  private List<ActionTask> workflowRuns;

  public ActionTaskResponse totalCount(Long totalCount) {
    this.totalCount = totalCount;
    return this;
  }

  /**
   * Get totalCount
   *
   * @return totalCount
   **/
  @Schema(description = "")
  public Long getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Long totalCount) {
    this.totalCount = totalCount;
  }

  public ActionTaskResponse workflowRuns(List<ActionTask> workflowRuns) {
    this.workflowRuns = workflowRuns;
    return this;
  }

  public ActionTaskResponse addWorkflowRunsItem(ActionTask workflowRunsItem) {
    if (this.workflowRuns == null) {
      this.workflowRuns = new ArrayList<ActionTask>();
    }
    this.workflowRuns.add(workflowRunsItem);
    return this;
  }

  /**
   * Get workflowRuns
   *
   * @return workflowRuns
   **/
  @Schema(description = "")
  public List<ActionTask> getWorkflowRuns() {
    return workflowRuns;
  }

  public void setWorkflowRuns(List<ActionTask> workflowRuns) {
    this.workflowRuns = workflowRuns;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionTaskResponse actionTaskResponse = (ActionTaskResponse) o;
    return Objects.equals(this.totalCount, actionTaskResponse.totalCount) &&
           Objects.equals(this.workflowRuns, actionTaskResponse.workflowRuns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalCount, workflowRuns);
  }


  @Override
  public String toString() {

    String sb = "class ActionTaskResponse {\n" +
                "    totalCount: " + toIndentedString(totalCount) + "\n" +
                "    workflowRuns: " + toIndentedString(workflowRuns) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
