/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * ActivityPub type
 */
@Schema(description = "ActivityPub type")
public class ActivityPub {
  @SerializedName("@context")
  private String _atContext;

  public ActivityPub _atContext(String _atContext) {
    this._atContext = _atContext;
    return this;
  }

  /**
   * Get _atContext
   *
   * @return _atContext
   **/
  @Schema(description = "")
  public String getAtContext() {
    return _atContext;
  }

  public void setAtContext(String _atContext) {
    this._atContext = _atContext;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivityPub activityPub = (ActivityPub) o;
    return Objects.equals(this._atContext, activityPub._atContext);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_atContext);
  }


  @Override
  public String toString() {

    String sb = "class ActivityPub {\n" +
                "    _atContext: " + toIndentedString(_atContext) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
