/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * AddTimeOption options for adding time to an issue
 */
@Schema(description = "AddTimeOption options for adding time to an issue")
public class AddTimeOption {
  @SerializedName("created")
  private OffsetDateTime created;

  @SerializedName("time")
  private Long time;

  @SerializedName("user_name")
  private String userName;

  public AddTimeOption created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

  /**
   * Get created
   *
   * @return created
   **/
  @Schema(description = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public AddTimeOption time(Long time) {
    this.time = time;
    return this;
  }

  /**
   * time in seconds
   *
   * @return time
   **/
  @Schema(required = true, description = "time in seconds")
  public Long getTime() {
    return time;
  }

  public void setTime(Long time) {
    this.time = time;
  }

  public AddTimeOption userName(String userName) {
    this.userName = userName;
    return this;
  }

  /**
   * User who spent the time (optional)
   *
   * @return userName
   **/
  @Schema(description = "User who spent the time (optional)")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddTimeOption addTimeOption = (AddTimeOption) o;
    return Objects.equals(this.created, addTimeOption.created) &&
           Objects.equals(this.time, addTimeOption.time) &&
           Objects.equals(this.userName, addTimeOption.userName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, time, userName);
  }


  @Override
  public String toString() {

    String sb = "class AddTimeOption {\n" +
                "    created: " + toIndentedString(created) + "\n" +
                "    time: " + toIndentedString(time) + "\n" +
                "    userName: " + toIndentedString(userName) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
