/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * Attachment a generic attachment
 */
@Schema(description = "Attachment a generic attachment")
public class Attachment {
  @SerializedName("browser_download_url")
  private String browserDownloadUrl;

  @SerializedName("created_at")
  private OffsetDateTime createdAt;

  @SerializedName("download_count")
  private Long downloadCount;

  @SerializedName("id")
  private Long id;

  @SerializedName("name")
  private String name;

  @SerializedName("size")
  private Long size;

  @SerializedName("uuid")
  private String uuid;

  public Attachment browserDownloadUrl(String browserDownloadUrl) {
    this.browserDownloadUrl = browserDownloadUrl;
    return this;
  }

  /**
   * Get browserDownloadUrl
   *
   * @return browserDownloadUrl
   **/
  @Schema(description = "")
  public String getBrowserDownloadUrl() {
    return browserDownloadUrl;
  }

  public void setBrowserDownloadUrl(String browserDownloadUrl) {
    this.browserDownloadUrl = browserDownloadUrl;
  }

  public Attachment createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   *
   * @return createdAt
   **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Attachment downloadCount(Long downloadCount) {
    this.downloadCount = downloadCount;
    return this;
  }

  /**
   * Get downloadCount
   *
   * @return downloadCount
   **/
  @Schema(description = "")
  public Long getDownloadCount() {
    return downloadCount;
  }

  public void setDownloadCount(Long downloadCount) {
    this.downloadCount = downloadCount;
  }

  public Attachment id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Attachment name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Attachment size(Long size) {
    this.size = size;
    return this;
  }

  /**
   * Get size
   *
   * @return size
   **/
  @Schema(description = "")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public Attachment uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

  /**
   * Get uuid
   *
   * @return uuid
   **/
  @Schema(description = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Attachment attachment = (Attachment) o;
    return Objects.equals(this.browserDownloadUrl, attachment.browserDownloadUrl) &&
           Objects.equals(this.createdAt, attachment.createdAt) &&
           Objects.equals(this.downloadCount, attachment.downloadCount) &&
           Objects.equals(this.id, attachment.id) &&
           Objects.equals(this.name, attachment.name) &&
           Objects.equals(this.size, attachment.size) &&
           Objects.equals(this.uuid, attachment.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(browserDownloadUrl, createdAt, downloadCount, id, name, size, uuid);
  }


  @Override
  public String toString() {

    String sb = "class Attachment {\n" +
                "    browserDownloadUrl: " + toIndentedString(browserDownloadUrl) + "\n" +
                "    createdAt: " + toIndentedString(createdAt) + "\n" +
                "    downloadCount: " + toIndentedString(downloadCount) + "\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    size: " + toIndentedString(size) + "\n" +
                "    uuid: " + toIndentedString(uuid) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
