/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Commit
 */

public class Commit {
  @SerializedName("author")
  private User author;

  @SerializedName("commit")
  private RepoCommit commit;

  @SerializedName("committer")
  private User committer;

  @SerializedName("created")
  private OffsetDateTime created;

  @SerializedName("files")
  private List<CommitAffectedFiles> files;

  @SerializedName("html_url")
  private String htmlUrl;

  @SerializedName("parents")
  private List<CommitMeta> parents;

  @SerializedName("sha")
  private String sha;

  @SerializedName("stats")
  private CommitStats stats;

  @SerializedName("url")
  private String url;

  public Commit author(User author) {
    this.author = author;
    return this;
  }

  /**
   * Get author
   *
   * @return author
   **/
  @Schema(description = "")
  public User getAuthor() {
    return author;
  }

  public void setAuthor(User author) {
    this.author = author;
  }

  public Commit commit(RepoCommit commit) {
    this.commit = commit;
    return this;
  }

  /**
   * Get commit
   *
   * @return commit
   **/
  @Schema(description = "")
  public RepoCommit getCommit() {
    return commit;
  }

  public void setCommit(RepoCommit commit) {
    this.commit = commit;
  }

  public Commit committer(User committer) {
    this.committer = committer;
    return this;
  }

  /**
   * Get committer
   *
   * @return committer
   **/
  @Schema(description = "")
  public User getCommitter() {
    return committer;
  }

  public void setCommitter(User committer) {
    this.committer = committer;
  }

  public Commit created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

  /**
   * Get created
   *
   * @return created
   **/
  @Schema(description = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public Commit files(List<CommitAffectedFiles> files) {
    this.files = files;
    return this;
  }

  public Commit addFilesItem(CommitAffectedFiles filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<CommitAffectedFiles>();
    }
    this.files.add(filesItem);
    return this;
  }

  /**
   * Get files
   *
   * @return files
   **/
  @Schema(description = "")
  public List<CommitAffectedFiles> getFiles() {
    return files;
  }

  public void setFiles(List<CommitAffectedFiles> files) {
    this.files = files;
  }

  public Commit htmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

  /**
   * Get htmlUrl
   *
   * @return htmlUrl
   **/
  @Schema(description = "")
  public String getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public Commit parents(List<CommitMeta> parents) {
    this.parents = parents;
    return this;
  }

  public Commit addParentsItem(CommitMeta parentsItem) {
    if (this.parents == null) {
      this.parents = new ArrayList<CommitMeta>();
    }
    this.parents.add(parentsItem);
    return this;
  }

  /**
   * Get parents
   *
   * @return parents
   **/
  @Schema(description = "")
  public List<CommitMeta> getParents() {
    return parents;
  }

  public void setParents(List<CommitMeta> parents) {
    this.parents = parents;
  }

  public Commit sha(String sha) {
    this.sha = sha;
    return this;
  }

  /**
   * Get sha
   *
   * @return sha
   **/
  @Schema(description = "")
  public String getSha() {
    return sha;
  }

  public void setSha(String sha) {
    this.sha = sha;
  }

  public Commit stats(CommitStats stats) {
    this.stats = stats;
    return this;
  }

  /**
   * Get stats
   *
   * @return stats
   **/
  @Schema(description = "")
  public CommitStats getStats() {
    return stats;
  }

  public void setStats(CommitStats stats) {
    this.stats = stats;
  }

  public Commit url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   *
   * @return url
   **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Commit commit = (Commit) o;
    return Objects.equals(this.author, commit.author) &&
           Objects.equals(this.commit, commit.commit) &&
           Objects.equals(this.committer, commit.committer) &&
           Objects.equals(this.created, commit.created) &&
           Objects.equals(this.files, commit.files) &&
           Objects.equals(this.htmlUrl, commit.htmlUrl) &&
           Objects.equals(this.parents, commit.parents) &&
           Objects.equals(this.sha, commit.sha) &&
           Objects.equals(this.stats, commit.stats) &&
           Objects.equals(this.url, commit.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(author, commit, committer, created, files, htmlUrl, parents, sha, stats, url);
  }


  @Override
  public String toString() {

    String sb = "class Commit {\n" +
                "    author: " + toIndentedString(author) + "\n" +
                "    commit: " + toIndentedString(commit) + "\n" +
                "    committer: " + toIndentedString(committer) + "\n" +
                "    created: " + toIndentedString(created) + "\n" +
                "    files: " + toIndentedString(files) + "\n" +
                "    htmlUrl: " + toIndentedString(htmlUrl) + "\n" +
                "    parents: " + toIndentedString(parents) + "\n" +
                "    sha: " + toIndentedString(sha) + "\n" +
                "    stats: " + toIndentedString(stats) + "\n" +
                "    url: " + toIndentedString(url) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
