/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * CreateOrUpdateSecretOption options when creating or updating secret
 */
@Schema(description = "CreateOrUpdateSecretOption options when creating or updating secret")
public class CreateOrUpdateSecretOption {
  @SerializedName("data")
  private String data;

  public CreateOrUpdateSecretOption data(String data) {
    this.data = data;
    return this;
  }

  /**
   * Data of the secret to update
   *
   * @return data
   **/
  @Schema(required = true, description = "Data of the secret to update")
  public String getData() {
    return data;
  }

  public void setData(String data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateOrUpdateSecretOption createOrUpdateSecretOption = (CreateOrUpdateSecretOption) o;
    return Objects.equals(this.data, createOrUpdateSecretOption.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data);
  }


  @Override
  public String toString() {

    String sb = "class CreateOrUpdateSecretOption {\n" +
                "    data: " + toIndentedString(data) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
