/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CreatePullRequestOption options when creating a pull request
 */
@Schema(description = "CreatePullRequestOption options when creating a pull request")
public class CreatePullRequestOption {
  @SerializedName("assignee")
  private String assignee;

  @SerializedName("assignees")
  private List<String> assignees;

  @SerializedName("base")
  private String base;

  @SerializedName("body")
  private String body;

  @SerializedName("due_date")
  private OffsetDateTime dueDate;

  @SerializedName("head")
  private String head;

  @SerializedName("labels")
  private List<Long> labels;

  @SerializedName("milestone")
  private Long milestone;

  @SerializedName("reviewers")
  private List<String> reviewers;

  @SerializedName("team_reviewers")
  private List<String> teamReviewers;

  @SerializedName("title")
  private String title;

  public CreatePullRequestOption assignee(String assignee) {
    this.assignee = assignee;
    return this;
  }

  /**
   * Get assignee
   *
   * @return assignee
   **/
  @Schema(description = "")
  public String getAssignee() {
    return assignee;
  }

  public void setAssignee(String assignee) {
    this.assignee = assignee;
  }

  public CreatePullRequestOption assignees(List<String> assignees) {
    this.assignees = assignees;
    return this;
  }

  public CreatePullRequestOption addAssigneesItem(String assigneesItem) {
    if (this.assignees == null) {
      this.assignees = new ArrayList<String>();
    }
    this.assignees.add(assigneesItem);
    return this;
  }

  /**
   * Get assignees
   *
   * @return assignees
   **/
  @Schema(description = "")
  public List<String> getAssignees() {
    return assignees;
  }

  public void setAssignees(List<String> assignees) {
    this.assignees = assignees;
  }

  public CreatePullRequestOption base(String base) {
    this.base = base;
    return this;
  }

  /**
   * Get base
   *
   * @return base
   **/
  @Schema(description = "")
  public String getBase() {
    return base;
  }

  public void setBase(String base) {
    this.base = base;
  }

  public CreatePullRequestOption body(String body) {
    this.body = body;
    return this;
  }

  /**
   * Get body
   *
   * @return body
   **/
  @Schema(description = "")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public CreatePullRequestOption dueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
    return this;
  }

  /**
   * Get dueDate
   *
   * @return dueDate
   **/
  @Schema(description = "")
  public OffsetDateTime getDueDate() {
    return dueDate;
  }

  public void setDueDate(OffsetDateTime dueDate) {
    this.dueDate = dueDate;
  }

  public CreatePullRequestOption head(String head) {
    this.head = head;
    return this;
  }

  /**
   * Get head
   *
   * @return head
   **/
  @Schema(description = "")
  public String getHead() {
    return head;
  }

  public void setHead(String head) {
    this.head = head;
  }

  public CreatePullRequestOption labels(List<Long> labels) {
    this.labels = labels;
    return this;
  }

  public CreatePullRequestOption addLabelsItem(Long labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<Long>();
    }
    this.labels.add(labelsItem);
    return this;
  }

  /**
   * Get labels
   *
   * @return labels
   **/
  @Schema(description = "")
  public List<Long> getLabels() {
    return labels;
  }

  public void setLabels(List<Long> labels) {
    this.labels = labels;
  }

  public CreatePullRequestOption milestone(Long milestone) {
    this.milestone = milestone;
    return this;
  }

  /**
   * Get milestone
   *
   * @return milestone
   **/
  @Schema(description = "")
  public Long getMilestone() {
    return milestone;
  }

  public void setMilestone(Long milestone) {
    this.milestone = milestone;
  }

  public CreatePullRequestOption reviewers(List<String> reviewers) {
    this.reviewers = reviewers;
    return this;
  }

  public CreatePullRequestOption addReviewersItem(String reviewersItem) {
    if (this.reviewers == null) {
      this.reviewers = new ArrayList<String>();
    }
    this.reviewers.add(reviewersItem);
    return this;
  }

  /**
   * Get reviewers
   *
   * @return reviewers
   **/
  @Schema(description = "")
  public List<String> getReviewers() {
    return reviewers;
  }

  public void setReviewers(List<String> reviewers) {
    this.reviewers = reviewers;
  }

  public CreatePullRequestOption teamReviewers(List<String> teamReviewers) {
    this.teamReviewers = teamReviewers;
    return this;
  }

  public CreatePullRequestOption addTeamReviewersItem(String teamReviewersItem) {
    if (this.teamReviewers == null) {
      this.teamReviewers = new ArrayList<String>();
    }
    this.teamReviewers.add(teamReviewersItem);
    return this;
  }

  /**
   * Get teamReviewers
   *
   * @return teamReviewers
   **/
  @Schema(description = "")
  public List<String> getTeamReviewers() {
    return teamReviewers;
  }

  public void setTeamReviewers(List<String> teamReviewers) {
    this.teamReviewers = teamReviewers;
  }

  public CreatePullRequestOption title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   *
   * @return title
   **/
  @Schema(description = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePullRequestOption createPullRequestOption = (CreatePullRequestOption) o;
    return Objects.equals(this.assignee, createPullRequestOption.assignee) &&
           Objects.equals(this.assignees, createPullRequestOption.assignees) &&
           Objects.equals(this.base, createPullRequestOption.base) &&
           Objects.equals(this.body, createPullRequestOption.body) &&
           Objects.equals(this.dueDate, createPullRequestOption.dueDate) &&
           Objects.equals(this.head, createPullRequestOption.head) &&
           Objects.equals(this.labels, createPullRequestOption.labels) &&
           Objects.equals(this.milestone, createPullRequestOption.milestone) &&
           Objects.equals(this.reviewers, createPullRequestOption.reviewers) &&
           Objects.equals(this.teamReviewers, createPullRequestOption.teamReviewers) &&
           Objects.equals(this.title, createPullRequestOption.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assignee, assignees, base, body, dueDate, head, labels, milestone, reviewers, teamReviewers, title);
  }


  @Override
  public String toString() {

    String sb = "class CreatePullRequestOption {\n" +
                "    assignee: " + toIndentedString(assignee) + "\n" +
                "    assignees: " + toIndentedString(assignees) + "\n" +
                "    base: " + toIndentedString(base) + "\n" +
                "    body: " + toIndentedString(body) + "\n" +
                "    dueDate: " + toIndentedString(dueDate) + "\n" +
                "    head: " + toIndentedString(head) + "\n" +
                "    labels: " + toIndentedString(labels) + "\n" +
                "    milestone: " + toIndentedString(milestone) + "\n" +
                "    reviewers: " + toIndentedString(reviewers) + "\n" +
                "    teamReviewers: " + toIndentedString(teamReviewers) + "\n" +
                "    title: " + toIndentedString(title) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
