/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * CreateTagOption options when creating a tag
 */
@Schema(description = "CreateTagOption options when creating a tag")
public class CreateTagOption {
  @SerializedName("message")
  private String message;

  @SerializedName("tag_name")
  private String tagName;

  @SerializedName("target")
  private String target;

  public CreateTagOption message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   *
   * @return message
   **/
  @Schema(description = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public CreateTagOption tagName(String tagName) {
    this.tagName = tagName;
    return this;
  }

  /**
   * Get tagName
   *
   * @return tagName
   **/
  @Schema(required = true, description = "")
  public String getTagName() {
    return tagName;
  }

  public void setTagName(String tagName) {
    this.tagName = tagName;
  }

  public CreateTagOption target(String target) {
    this.target = target;
    return this;
  }

  /**
   * Get target
   *
   * @return target
   **/
  @Schema(description = "")
  public String getTarget() {
    return target;
  }

  public void setTarget(String target) {
    this.target = target;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTagOption createTagOption = (CreateTagOption) o;
    return Objects.equals(this.message, createTagOption.message) &&
           Objects.equals(this.tagName, createTagOption.tagName) &&
           Objects.equals(this.target, createTagOption.target);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, tagName, target);
  }


  @Override
  public String toString() {

    String sb = "class CreateTagOption {\n" +
                "    message: " + toIndentedString(message) + "\n" +
                "    tagName: " + toIndentedString(tagName) + "\n" +
                "    target: " + toIndentedString(target) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
