/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * CreateStatusOption holds the information needed to create a new CommitStatus for a Commit
 */
@Schema(description = "CreateStatusOption holds the information needed to create a new CommitStatus for a Commit")
public class CreateStatusOption {
  @SerializedName("context")
  private String context;

  @SerializedName("description")
  private String description;

  @SerializedName("state")
  private String state;

  @SerializedName("target_url")
  private String targetUrl;

  public CreateStatusOption context(String context) {
    this.context = context;
    return this;
  }

  /**
   * Get context
   *
   * @return context
   **/
  @Schema(description = "")
  public String getContext() {
    return context;
  }

  public void setContext(String context) {
    this.context = context;
  }

  public CreateStatusOption description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   *
   * @return description
   **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateStatusOption state(String state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   *
   * @return state
   **/
  @Schema(description = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public CreateStatusOption targetUrl(String targetUrl) {
    this.targetUrl = targetUrl;
    return this;
  }

  /**
   * Get targetUrl
   *
   * @return targetUrl
   **/
  @Schema(description = "")
  public String getTargetUrl() {
    return targetUrl;
  }

  public void setTargetUrl(String targetUrl) {
    this.targetUrl = targetUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateStatusOption createStatusOption = (CreateStatusOption) o;
    return Objects.equals(this.context, createStatusOption.context) &&
           Objects.equals(this.description, createStatusOption.description) &&
           Objects.equals(this.state, createStatusOption.state) &&
           Objects.equals(this.targetUrl, createStatusOption.targetUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, description, state, targetUrl);
  }


  @Override
  public String toString() {

    String sb = "class CreateStatusOption {\n" +
                "    context: " + toIndentedString(context) + "\n" +
                "    description: " + toIndentedString(description) + "\n" +
                "    state: " + toIndentedString(state) + "\n" +
                "    targetUrl: " + toIndentedString(targetUrl) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
