/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * DismissPullReviewOptions are options to dismiss a pull review
 */
@Schema(description = "DismissPullReviewOptions are options to dismiss a pull review")
public class DismissPullReviewOptions {
  @SerializedName("message")
  private String message;

  @SerializedName("priors")
  private Boolean priors;

  public DismissPullReviewOptions message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   *
   * @return message
   **/
  @Schema(description = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public DismissPullReviewOptions priors(Boolean priors) {
    this.priors = priors;
    return this;
  }

  /**
   * Get priors
   *
   * @return priors
   **/
  @Schema(description = "")
  public Boolean isPriors() {
    return priors;
  }

  public void setPriors(Boolean priors) {
    this.priors = priors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DismissPullReviewOptions dismissPullReviewOptions = (DismissPullReviewOptions) o;
    return Objects.equals(this.message, dismissPullReviewOptions.message) &&
           Objects.equals(this.priors, dismissPullReviewOptions.priors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, priors);
  }


  @Override
  public String toString() {

    String sb = "class DismissPullReviewOptions {\n" +
                "    message: " + toIndentedString(message) + "\n" +
                "    priors: " + toIndentedString(priors) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
