/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * EditLabelOption options for editing a label
 */
@Schema(description = "EditLabelOption options for editing a label")
public class EditLabelOption {
  @SerializedName("color")
  private String color;

  @SerializedName("description")
  private String description;

  @SerializedName("exclusive")
  private Boolean exclusive;

  @SerializedName("is_archived")
  private Boolean isArchived;

  @SerializedName("name")
  private String name;

  public EditLabelOption color(String color) {
    this.color = color;
    return this;
  }

  /**
   * Get color
   *
   * @return color
   **/
  @Schema(example = "#00aabb", description = "")
  public String getColor() {
    return color;
  }

  public void setColor(String color) {
    this.color = color;
  }

  public EditLabelOption description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   *
   * @return description
   **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public EditLabelOption exclusive(Boolean exclusive) {
    this.exclusive = exclusive;
    return this;
  }

  /**
   * Get exclusive
   *
   * @return exclusive
   **/
  @Schema(example = "false", description = "")
  public Boolean isExclusive() {
    return exclusive;
  }

  public void setExclusive(Boolean exclusive) {
    this.exclusive = exclusive;
  }

  public EditLabelOption isArchived(Boolean isArchived) {
    this.isArchived = isArchived;
    return this;
  }

  /**
   * Get isArchived
   *
   * @return isArchived
   **/
  @Schema(example = "false", description = "")
  public Boolean isIsArchived() {
    return isArchived;
  }

  public void setIsArchived(Boolean isArchived) {
    this.isArchived = isArchived;
  }

  public EditLabelOption name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditLabelOption editLabelOption = (EditLabelOption) o;
    return Objects.equals(this.color, editLabelOption.color) &&
           Objects.equals(this.description, editLabelOption.description) &&
           Objects.equals(this.exclusive, editLabelOption.exclusive) &&
           Objects.equals(this.isArchived, editLabelOption.isArchived) &&
           Objects.equals(this.name, editLabelOption.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(color, description, exclusive, isArchived, name);
  }


  @Override
  public String toString() {

    String sb = "class EditLabelOption {\n" +
                "    color: " + toIndentedString(color) + "\n" +
                "    description: " + toIndentedString(description) + "\n" +
                "    exclusive: " + toIndentedString(exclusive) + "\n" +
                "    isArchived: " + toIndentedString(isArchived) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
