/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * GitignoreTemplateInfo name and text of a gitignore template
 */
@Schema(description = "GitignoreTemplateInfo name and text of a gitignore template")
public class GitignoreTemplateInfo {
  @SerializedName("name")
  private String name;

  @SerializedName("source")
  private String source;

  public GitignoreTemplateInfo name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GitignoreTemplateInfo source(String source) {
    this.source = source;
    return this;
  }

  /**
   * Get source
   *
   * @return source
   **/
  @Schema(description = "")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GitignoreTemplateInfo gitignoreTemplateInfo = (GitignoreTemplateInfo) o;
    return Objects.equals(this.name, gitignoreTemplateInfo.name) &&
           Objects.equals(this.source, gitignoreTemplateInfo.source);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, source);
  }


  @Override
  public String toString() {

    String sb = "class GitignoreTemplateInfo {\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    source: " + toIndentedString(source) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
