/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.io.File;
import java.util.Objects;

/**
 * IdAssetsBody
 */

public class IdAssetsBody {
  @SerializedName("attachment")
  private File attachment;

  public IdAssetsBody attachment(File attachment) {
    this.attachment = attachment;
    return this;
  }

  /**
   * attachment to upload
   *
   * @return attachment
   **/
  @Schema(required = true, description = "attachment to upload")
  public File getAttachment() {
    return attachment;
  }

  public void setAttachment(File attachment) {
    this.attachment = attachment;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdAssetsBody idAssetsBody = (IdAssetsBody) o;
    return Objects.equals(this.attachment, idAssetsBody.attachment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Objects.hashCode(attachment));
  }


  @Override
  public String toString() {

    String sb = "class IdAssetsBody {\n" +
                "    attachment: " + toIndentedString(attachment) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
