/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * IssueFormField represents a form field
 */
@Schema(description = "IssueFormField represents a form field")
public class IssueFormField {
  @SerializedName("attributes")
  private Map<String, Object> attributes;

  @SerializedName("id")
  private String id;

  @SerializedName("type")
  private String type;

  @SerializedName("validations")
  private Map<String, Object> validations;

  @SerializedName("visible")
  private List<String> visible;

  public IssueFormField attributes(Map<String, Object> attributes) {
    this.attributes = attributes;
    return this;
  }

  public IssueFormField putAttributesItem(String key, Object attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<String, Object>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

  /**
   * Get attributes
   *
   * @return attributes
   **/
  @Schema(description = "")
  public Map<String, Object> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, Object> attributes) {
    this.attributes = attributes;
  }

  public IssueFormField id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public IssueFormField type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   *
   * @return type
   **/
  @Schema(description = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public IssueFormField validations(Map<String, Object> validations) {
    this.validations = validations;
    return this;
  }

  public IssueFormField putValidationsItem(String key, Object validationsItem) {
    if (this.validations == null) {
      this.validations = new HashMap<String, Object>();
    }
    this.validations.put(key, validationsItem);
    return this;
  }

  /**
   * Get validations
   *
   * @return validations
   **/
  @Schema(description = "")
  public Map<String, Object> getValidations() {
    return validations;
  }

  public void setValidations(Map<String, Object> validations) {
    this.validations = validations;
  }

  public IssueFormField visible(List<String> visible) {
    this.visible = visible;
    return this;
  }

  public IssueFormField addVisibleItem(String visibleItem) {
    if (this.visible == null) {
      this.visible = new ArrayList<String>();
    }
    this.visible.add(visibleItem);
    return this;
  }

  /**
   * Get visible
   *
   * @return visible
   **/
  @Schema(description = "")
  public List<String> getVisible() {
    return visible;
  }

  public void setVisible(List<String> visible) {
    this.visible = visible;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueFormField issueFormField = (IssueFormField) o;
    return Objects.equals(this.attributes, issueFormField.attributes) &&
           Objects.equals(this.id, issueFormField.id) &&
           Objects.equals(this.type, issueFormField.type) &&
           Objects.equals(this.validations, issueFormField.validations) &&
           Objects.equals(this.visible, issueFormField.visible);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributes, id, type, validations, visible);
  }


  @Override
  public String toString() {

    String sb = "class IssueFormField {\n" +
                "    attributes: " + toIndentedString(attributes) + "\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    type: " + toIndentedString(type) + "\n" +
                "    validations: " + toIndentedString(validations) + "\n" +
                "    visible: " + toIndentedString(visible) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
