/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * IssueConfigContactLink
 */

public class IssueConfigContactLink {
  @SerializedName("about")
  private String about;

  @SerializedName("name")
  private String name;

  @SerializedName("url")
  private String url;

  public IssueConfigContactLink about(String about) {
    this.about = about;
    return this;
  }

  /**
   * Get about
   *
   * @return about
   **/
  @Schema(description = "")
  public String getAbout() {
    return about;
  }

  public void setAbout(String about) {
    this.about = about;
  }

  public IssueConfigContactLink name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public IssueConfigContactLink url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   *
   * @return url
   **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueConfigContactLink issueConfigContactLink = (IssueConfigContactLink) o;
    return Objects.equals(this.about, issueConfigContactLink.about) &&
           Objects.equals(this.name, issueConfigContactLink.name) &&
           Objects.equals(this.url, issueConfigContactLink.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(about, name, url);
  }


  @Override
  public String toString() {

    String sb = "class IssueConfigContactLink {\n" +
                "    about: " + toIndentedString(about) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    url: " + toIndentedString(url) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
