/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * IssueConfigValidation
 */

public class IssueConfigValidation {
  @SerializedName("message")
  private String message;

  @SerializedName("valid")
  private Boolean valid;

  public IssueConfigValidation message(String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   *
   * @return message
   **/
  @Schema(description = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public IssueConfigValidation valid(Boolean valid) {
    this.valid = valid;
    return this;
  }

  /**
   * Get valid
   *
   * @return valid
   **/
  @Schema(description = "")
  public Boolean isValid() {
    return valid;
  }

  public void setValid(Boolean valid) {
    this.valid = valid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueConfigValidation issueConfigValidation = (IssueConfigValidation) o;
    return Objects.equals(this.message, issueConfigValidation.message) &&
           Objects.equals(this.valid, issueConfigValidation.valid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, valid);
  }


  @Override
  public String toString() {

    String sb = "class IssueConfigValidation {\n" +
                "    message: " + toIndentedString(message) + "\n" +
                "    valid: " + toIndentedString(valid) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
