/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * LicensesListEntry is used for the API
 */
@Schema(description = "LicensesListEntry is used for the API")
public class LicensesTemplateListEntry {
  @SerializedName("key")
  private String key;

  @SerializedName("name")
  private String name;

  @SerializedName("url")
  private String url;

  public LicensesTemplateListEntry key(String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   *
   * @return key
   **/
  @Schema(description = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public LicensesTemplateListEntry name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LicensesTemplateListEntry url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   *
   * @return url
   **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicensesTemplateListEntry licensesTemplateListEntry = (LicensesTemplateListEntry) o;
    return Objects.equals(this.key, licensesTemplateListEntry.key) &&
           Objects.equals(this.name, licensesTemplateListEntry.name) &&
           Objects.equals(this.url, licensesTemplateListEntry.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, name, url);
  }


  @Override
  public String toString() {

    String sb = "class LicensesTemplateListEntry {\n" +
                "    key: " + toIndentedString(key) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    url: " + toIndentedString(url) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
