/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * LicensesInfo contains information about a License
 */
@Schema(description = "LicensesInfo contains information about a License")
public class LicenseTemplateInfo {
  @SerializedName("body")
  private String body;

  @SerializedName("implementation")
  private String implementation;

  @SerializedName("key")
  private String key;

  @SerializedName("name")
  private String name;

  @SerializedName("url")
  private String url;

  public LicenseTemplateInfo body(String body) {
    this.body = body;
    return this;
  }

  /**
   * Get body
   *
   * @return body
   **/
  @Schema(description = "")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public LicenseTemplateInfo implementation(String implementation) {
    this.implementation = implementation;
    return this;
  }

  /**
   * Get implementation
   *
   * @return implementation
   **/
  @Schema(description = "")
  public String getImplementation() {
    return implementation;
  }

  public void setImplementation(String implementation) {
    this.implementation = implementation;
  }

  public LicenseTemplateInfo key(String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   *
   * @return key
   **/
  @Schema(description = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public LicenseTemplateInfo name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LicenseTemplateInfo url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   *
   * @return url
   **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenseTemplateInfo licenseTemplateInfo = (LicenseTemplateInfo) o;
    return Objects.equals(this.body, licenseTemplateInfo.body) &&
           Objects.equals(this.implementation, licenseTemplateInfo.implementation) &&
           Objects.equals(this.key, licenseTemplateInfo.key) &&
           Objects.equals(this.name, licenseTemplateInfo.name) &&
           Objects.equals(this.url, licenseTemplateInfo.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body, implementation, key, name, url);
  }


  @Override
  public String toString() {

    String sb = "class LicenseTemplateInfo {\n" +
                "    body: " + toIndentedString(body) + "\n" +
                "    implementation: " + toIndentedString(implementation) + "\n" +
                "    key: " + toIndentedString(key) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    url: " + toIndentedString(url) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
