/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * MarkupOption markup options
 */
@Schema(description = "MarkupOption markup options")
public class MarkupOption {
  @SerializedName("Context")
  private String context;

  @SerializedName("FilePath")
  private String filePath;

  @SerializedName("Mode")
  private String mode;

  @SerializedName("Text")
  private String text;

  @SerializedName("Wiki")
  private Boolean wiki;

  public MarkupOption context(String context) {
    this.context = context;
    return this;
  }

  /**
   * URL path for rendering issue, media and file links Expected format: /subpath/{user}/{repo}/src/{branch, commit, tag}/{identifier/path}/{file/dir}  in: body
   *
   * @return context
   **/
  @Schema(description = "URL path for rendering issue, media and file links Expected format: /subpath/{user}/{repo}/src/{branch, commit, tag}/{identifier/path}/{file/dir}  in: body")
  public String getContext() {
    return context;
  }

  public void setContext(String context) {
    this.context = context;
  }

  public MarkupOption filePath(String filePath) {
    this.filePath = filePath;
    return this;
  }

  /**
   * File path for detecting extension in file mode  in: body
   *
   * @return filePath
   **/
  @Schema(description = "File path for detecting extension in file mode  in: body")
  public String getFilePath() {
    return filePath;
  }

  public void setFilePath(String filePath) {
    this.filePath = filePath;
  }

  public MarkupOption mode(String mode) {
    this.mode = mode;
    return this;
  }

  /**
   * Mode to render (markdown, comment, wiki, file)  in: body
   *
   * @return mode
   **/
  @Schema(description = "Mode to render (markdown, comment, wiki, file)  in: body")
  public String getMode() {
    return mode;
  }

  public void setMode(String mode) {
    this.mode = mode;
  }

  public MarkupOption text(String text) {
    this.text = text;
    return this;
  }

  /**
   * Text markup to render  in: body
   *
   * @return text
   **/
  @Schema(description = "Text markup to render  in: body")
  public String getText() {
    return text;
  }

  public void setText(String text) {
    this.text = text;
  }

  public MarkupOption wiki(Boolean wiki) {
    this.wiki = wiki;
    return this;
  }

  /**
   * Is it a wiki page? (use mode&#x3D;wiki instead)  Deprecated: true in: body
   *
   * @return wiki
   **/
  @Schema(description = "Is it a wiki page? (use mode=wiki instead)  Deprecated: true in: body")
  public Boolean isWiki() {
    return wiki;
  }

  public void setWiki(Boolean wiki) {
    this.wiki = wiki;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarkupOption markupOption = (MarkupOption) o;
    return Objects.equals(this.context, markupOption.context) &&
           Objects.equals(this.filePath, markupOption.filePath) &&
           Objects.equals(this.mode, markupOption.mode) &&
           Objects.equals(this.text, markupOption.text) &&
           Objects.equals(this.wiki, markupOption.wiki);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, filePath, mode, text, wiki);
  }


  @Override
  public String toString() {

    String sb = "class MarkupOption {\n" +
                "    context: " + toIndentedString(context) + "\n" +
                "    filePath: " + toIndentedString(filePath) + "\n" +
                "    mode: " + toIndentedString(mode) + "\n" +
                "    text: " + toIndentedString(text) + "\n" +
                "    wiki: " + toIndentedString(wiki) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
