/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * NodeInfoUsageUsers contains statistics about the users of this server
 */
@Schema(description = "NodeInfoUsageUsers contains statistics about the users of this server")
public class NodeInfoUsageUsers {
  @SerializedName("activeHalfyear")
  private Long activeHalfyear;

  @SerializedName("activeMonth")
  private Long activeMonth;

  @SerializedName("total")
  private Long total;

  public NodeInfoUsageUsers activeHalfyear(Long activeHalfyear) {
    this.activeHalfyear = activeHalfyear;
    return this;
  }

  /**
   * Get activeHalfyear
   *
   * @return activeHalfyear
   **/
  @Schema(description = "")
  public Long getActiveHalfyear() {
    return activeHalfyear;
  }

  public void setActiveHalfyear(Long activeHalfyear) {
    this.activeHalfyear = activeHalfyear;
  }

  public NodeInfoUsageUsers activeMonth(Long activeMonth) {
    this.activeMonth = activeMonth;
    return this;
  }

  /**
   * Get activeMonth
   *
   * @return activeMonth
   **/
  @Schema(description = "")
  public Long getActiveMonth() {
    return activeMonth;
  }

  public void setActiveMonth(Long activeMonth) {
    this.activeMonth = activeMonth;
  }

  public NodeInfoUsageUsers total(Long total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   *
   * @return total
   **/
  @Schema(description = "")
  public Long getTotal() {
    return total;
  }

  public void setTotal(Long total) {
    this.total = total;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeInfoUsageUsers nodeInfoUsageUsers = (NodeInfoUsageUsers) o;
    return Objects.equals(this.activeHalfyear, nodeInfoUsageUsers.activeHalfyear) &&
           Objects.equals(this.activeMonth, nodeInfoUsageUsers.activeMonth) &&
           Objects.equals(this.total, nodeInfoUsageUsers.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeHalfyear, activeMonth, total);
  }


  @Override
  public String toString() {

    String sb = "class NodeInfoUsageUsers {\n" +
                "    activeHalfyear: " + toIndentedString(activeHalfyear) + "\n" +
                "    activeMonth: " + toIndentedString(activeMonth) + "\n" +
                "    total: " + toIndentedString(total) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
