/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * NotificationCount number of unread notifications
 */
@Schema(description = "NotificationCount number of unread notifications")
public class NotificationCount {
  @SerializedName("new")
  private Long _new;

  public NotificationCount _new(Long _new) {
    this._new = _new;
    return this;
  }

  /**
   * Get _new
   *
   * @return _new
   **/
  @Schema(description = "")
  public Long getNew() {
    return _new;
  }

  public void setNew(Long _new) {
    this._new = _new;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationCount notificationCount = (NotificationCount) o;
    return Objects.equals(this._new, notificationCount._new);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_new);
  }


  @Override
  public String toString() {

    String sb = "class NotificationCount {\n" +
                "    _new: " + toIndentedString(_new) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
