/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * OrganizationPermissions list different users permissions on an organization
 */
@Schema(description = "OrganizationPermissions list different users permissions on an organization")
public class OrganizationPermissions {
  @SerializedName("can_create_repository")
  private Boolean canCreateRepository;

  @SerializedName("can_read")
  private Boolean canRead;

  @SerializedName("can_write")
  private Boolean canWrite;

  @SerializedName("is_admin")
  private Boolean isAdmin;

  @SerializedName("is_owner")
  private Boolean isOwner;

  public OrganizationPermissions canCreateRepository(Boolean canCreateRepository) {
    this.canCreateRepository = canCreateRepository;
    return this;
  }

  /**
   * Get canCreateRepository
   *
   * @return canCreateRepository
   **/
  @Schema(description = "")
  public Boolean isCanCreateRepository() {
    return canCreateRepository;
  }

  public void setCanCreateRepository(Boolean canCreateRepository) {
    this.canCreateRepository = canCreateRepository;
  }

  public OrganizationPermissions canRead(Boolean canRead) {
    this.canRead = canRead;
    return this;
  }

  /**
   * Get canRead
   *
   * @return canRead
   **/
  @Schema(description = "")
  public Boolean isCanRead() {
    return canRead;
  }

  public void setCanRead(Boolean canRead) {
    this.canRead = canRead;
  }

  public OrganizationPermissions canWrite(Boolean canWrite) {
    this.canWrite = canWrite;
    return this;
  }

  /**
   * Get canWrite
   *
   * @return canWrite
   **/
  @Schema(description = "")
  public Boolean isCanWrite() {
    return canWrite;
  }

  public void setCanWrite(Boolean canWrite) {
    this.canWrite = canWrite;
  }

  public OrganizationPermissions isAdmin(Boolean isAdmin) {
    this.isAdmin = isAdmin;
    return this;
  }

  /**
   * Get isAdmin
   *
   * @return isAdmin
   **/
  @Schema(description = "")
  public Boolean isIsAdmin() {
    return isAdmin;
  }

  public void setIsAdmin(Boolean isAdmin) {
    this.isAdmin = isAdmin;
  }

  public OrganizationPermissions isOwner(Boolean isOwner) {
    this.isOwner = isOwner;
    return this;
  }

  /**
   * Get isOwner
   *
   * @return isOwner
   **/
  @Schema(description = "")
  public Boolean isIsOwner() {
    return isOwner;
  }

  public void setIsOwner(Boolean isOwner) {
    this.isOwner = isOwner;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrganizationPermissions organizationPermissions = (OrganizationPermissions) o;
    return Objects.equals(this.canCreateRepository, organizationPermissions.canCreateRepository) &&
           Objects.equals(this.canRead, organizationPermissions.canRead) &&
           Objects.equals(this.canWrite, organizationPermissions.canWrite) &&
           Objects.equals(this.isAdmin, organizationPermissions.isAdmin) &&
           Objects.equals(this.isOwner, organizationPermissions.isOwner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canCreateRepository, canRead, canWrite, isAdmin, isOwner);
  }


  @Override
  public String toString() {

    String sb = "class OrganizationPermissions {\n" +
                "    canCreateRepository: " + toIndentedString(canCreateRepository) + "\n" +
                "    canRead: " + toIndentedString(canRead) + "\n" +
                "    canWrite: " + toIndentedString(canWrite) + "\n" +
                "    isAdmin: " + toIndentedString(isAdmin) + "\n" +
                "    isOwner: " + toIndentedString(isOwner) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
