/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * PackageFile represents a package file
 */
@Schema(description = "PackageFile represents a package file")
public class PackageFile {
  @SerializedName("Size")
  private Long size;

  @SerializedName("id")
  private Long id;

  @SerializedName("md5")
  private String md5;

  @SerializedName("name")
  private String name;

  @SerializedName("sha1")
  private String sha1;

  @SerializedName("sha256")
  private String sha256;

  @SerializedName("sha512")
  private String sha512;

  public PackageFile size(Long size) {
    this.size = size;
    return this;
  }

  /**
   * Get size
   *
   * @return size
   **/
  @Schema(description = "")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public PackageFile id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public PackageFile md5(String md5) {
    this.md5 = md5;
    return this;
  }

  /**
   * Get md5
   *
   * @return md5
   **/
  @Schema(description = "")
  public String getMd5() {
    return md5;
  }

  public void setMd5(String md5) {
    this.md5 = md5;
  }

  public PackageFile name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PackageFile sha1(String sha1) {
    this.sha1 = sha1;
    return this;
  }

  /**
   * Get sha1
   *
   * @return sha1
   **/
  @Schema(description = "")
  public String getSha1() {
    return sha1;
  }

  public void setSha1(String sha1) {
    this.sha1 = sha1;
  }

  public PackageFile sha256(String sha256) {
    this.sha256 = sha256;
    return this;
  }

  /**
   * Get sha256
   *
   * @return sha256
   **/
  @Schema(description = "")
  public String getSha256() {
    return sha256;
  }

  public void setSha256(String sha256) {
    this.sha256 = sha256;
  }

  public PackageFile sha512(String sha512) {
    this.sha512 = sha512;
    return this;
  }

  /**
   * Get sha512
   *
   * @return sha512
   **/
  @Schema(description = "")
  public String getSha512() {
    return sha512;
  }

  public void setSha512(String sha512) {
    this.sha512 = sha512;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageFile packageFile = (PackageFile) o;
    return Objects.equals(this.size, packageFile.size) &&
           Objects.equals(this.id, packageFile.id) &&
           Objects.equals(this.md5, packageFile.md5) &&
           Objects.equals(this.name, packageFile.name) &&
           Objects.equals(this.sha1, packageFile.sha1) &&
           Objects.equals(this.sha256, packageFile.sha256) &&
           Objects.equals(this.sha512, packageFile.sha512);
  }

  @Override
  public int hashCode() {
    return Objects.hash(size, id, md5, name, sha1, sha256, sha512);
  }


  @Override
  public String toString() {

    String sb = "class PackageFile {\n" +
                "    size: " + toIndentedString(size) + "\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    md5: " + toIndentedString(md5) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    sha1: " + toIndentedString(sha1) + "\n" +
                "    sha256: " + toIndentedString(sha256) + "\n" +
                "    sha512: " + toIndentedString(sha512) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
