/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * PayloadUser represents the author or committer of a commit
 */
@Schema(description = "PayloadUser represents the author or committer of a commit")
public class PayloadUser {
  @SerializedName("email")
  private String email;

  @SerializedName("name")
  private String name;

  @SerializedName("username")
  private String username;

  public PayloadUser email(String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   *
   * @return email
   **/
  @Schema(description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public PayloadUser name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Full name of the commit author
   *
   * @return name
   **/
  @Schema(description = "Full name of the commit author")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PayloadUser username(String username) {
    this.username = username;
    return this;
  }

  /**
   * Get username
   *
   * @return username
   **/
  @Schema(description = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayloadUser payloadUser = (PayloadUser) o;
    return Objects.equals(this.email, payloadUser.email) &&
           Objects.equals(this.name, payloadUser.name) &&
           Objects.equals(this.username, payloadUser.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, name, username);
  }


  @Override
  public String toString() {

    String sb = "class PayloadUser {\n" +
                "    email: " + toIndentedString(email) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    username: " + toIndentedString(username) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
