/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * PullRequestMeta PR info if an issue is a PR
 */
@Schema(description = "PullRequestMeta PR info if an issue is a PR")
public class PullRequestMeta {
  @SerializedName("draft")
  private Boolean draft;

  @SerializedName("html_url")
  private String htmlUrl;

  @SerializedName("merged")
  private Boolean merged;

  @SerializedName("merged_at")
  private OffsetDateTime mergedAt;

  public PullRequestMeta draft(Boolean draft) {
    this.draft = draft;
    return this;
  }

  /**
   * Get draft
   *
   * @return draft
   **/
  @Schema(description = "")
  public Boolean isDraft() {
    return draft;
  }

  public void setDraft(Boolean draft) {
    this.draft = draft;
  }

  public PullRequestMeta htmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

  /**
   * Get htmlUrl
   *
   * @return htmlUrl
   **/
  @Schema(description = "")
  public String getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public PullRequestMeta merged(Boolean merged) {
    this.merged = merged;
    return this;
  }

  /**
   * Get merged
   *
   * @return merged
   **/
  @Schema(description = "")
  public Boolean isMerged() {
    return merged;
  }

  public void setMerged(Boolean merged) {
    this.merged = merged;
  }

  public PullRequestMeta mergedAt(OffsetDateTime mergedAt) {
    this.mergedAt = mergedAt;
    return this;
  }

  /**
   * Get mergedAt
   *
   * @return mergedAt
   **/
  @Schema(description = "")
  public OffsetDateTime getMergedAt() {
    return mergedAt;
  }

  public void setMergedAt(OffsetDateTime mergedAt) {
    this.mergedAt = mergedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PullRequestMeta pullRequestMeta = (PullRequestMeta) o;
    return Objects.equals(this.draft, pullRequestMeta.draft) &&
           Objects.equals(this.htmlUrl, pullRequestMeta.htmlUrl) &&
           Objects.equals(this.merged, pullRequestMeta.merged) &&
           Objects.equals(this.mergedAt, pullRequestMeta.mergedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(draft, htmlUrl, merged, mergedAt);
  }


  @Override
  public String toString() {

    String sb = "class PullRequestMeta {\n" +
                "    draft: " + toIndentedString(draft) + "\n" +
                "    htmlUrl: " + toIndentedString(htmlUrl) + "\n" +
                "    merged: " + toIndentedString(merged) + "\n" +
                "    mergedAt: " + toIndentedString(mergedAt) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
