/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Release represents a repository release
 */
@Schema(description = "Release represents a repository release")
public class Release {
  @SerializedName("assets")
  private List<Attachment> assets;

  @SerializedName("author")
  private User author;

  @SerializedName("body")
  private String body;

  @SerializedName("created_at")
  private OffsetDateTime createdAt;

  @SerializedName("draft")
  private Boolean draft;

  @SerializedName("html_url")
  private String htmlUrl;

  @SerializedName("id")
  private Long id;

  @SerializedName("name")
  private String name;

  @SerializedName("prerelease")
  private Boolean prerelease;

  @SerializedName("published_at")
  private OffsetDateTime publishedAt;

  @SerializedName("tag_name")
  private String tagName;

  @SerializedName("tarball_url")
  private String tarballUrl;

  @SerializedName("target_commitish")
  private String targetCommitish;

  @SerializedName("upload_url")
  private String uploadUrl;

  @SerializedName("url")
  private String url;

  @SerializedName("zipball_url")
  private String zipballUrl;

  public Release assets(List<Attachment> assets) {
    this.assets = assets;
    return this;
  }

  public Release addAssetsItem(Attachment assetsItem) {
    if (this.assets == null) {
      this.assets = new ArrayList<Attachment>();
    }
    this.assets.add(assetsItem);
    return this;
  }

  /**
   * Get assets
   *
   * @return assets
   **/
  @Schema(description = "")
  public List<Attachment> getAssets() {
    return assets;
  }

  public void setAssets(List<Attachment> assets) {
    this.assets = assets;
  }

  public Release author(User author) {
    this.author = author;
    return this;
  }

  /**
   * Get author
   *
   * @return author
   **/
  @Schema(description = "")
  public User getAuthor() {
    return author;
  }

  public void setAuthor(User author) {
    this.author = author;
  }

  public Release body(String body) {
    this.body = body;
    return this;
  }

  /**
   * Get body
   *
   * @return body
   **/
  @Schema(description = "")
  public String getBody() {
    return body;
  }

  public void setBody(String body) {
    this.body = body;
  }

  public Release createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   *
   * @return createdAt
   **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Release draft(Boolean draft) {
    this.draft = draft;
    return this;
  }

  /**
   * Get draft
   *
   * @return draft
   **/
  @Schema(description = "")
  public Boolean isDraft() {
    return draft;
  }

  public void setDraft(Boolean draft) {
    this.draft = draft;
  }

  public Release htmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

  /**
   * Get htmlUrl
   *
   * @return htmlUrl
   **/
  @Schema(description = "")
  public String getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public Release id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Release name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Release prerelease(Boolean prerelease) {
    this.prerelease = prerelease;
    return this;
  }

  /**
   * Get prerelease
   *
   * @return prerelease
   **/
  @Schema(description = "")
  public Boolean isPrerelease() {
    return prerelease;
  }

  public void setPrerelease(Boolean prerelease) {
    this.prerelease = prerelease;
  }

  public Release publishedAt(OffsetDateTime publishedAt) {
    this.publishedAt = publishedAt;
    return this;
  }

  /**
   * Get publishedAt
   *
   * @return publishedAt
   **/
  @Schema(description = "")
  public OffsetDateTime getPublishedAt() {
    return publishedAt;
  }

  public void setPublishedAt(OffsetDateTime publishedAt) {
    this.publishedAt = publishedAt;
  }

  public Release tagName(String tagName) {
    this.tagName = tagName;
    return this;
  }

  /**
   * Get tagName
   *
   * @return tagName
   **/
  @Schema(description = "")
  public String getTagName() {
    return tagName;
  }

  public void setTagName(String tagName) {
    this.tagName = tagName;
  }

  public Release tarballUrl(String tarballUrl) {
    this.tarballUrl = tarballUrl;
    return this;
  }

  /**
   * Get tarballUrl
   *
   * @return tarballUrl
   **/
  @Schema(description = "")
  public String getTarballUrl() {
    return tarballUrl;
  }

  public void setTarballUrl(String tarballUrl) {
    this.tarballUrl = tarballUrl;
  }

  public Release targetCommitish(String targetCommitish) {
    this.targetCommitish = targetCommitish;
    return this;
  }

  /**
   * Get targetCommitish
   *
   * @return targetCommitish
   **/
  @Schema(description = "")
  public String getTargetCommitish() {
    return targetCommitish;
  }

  public void setTargetCommitish(String targetCommitish) {
    this.targetCommitish = targetCommitish;
  }

  public Release uploadUrl(String uploadUrl) {
    this.uploadUrl = uploadUrl;
    return this;
  }

  /**
   * Get uploadUrl
   *
   * @return uploadUrl
   **/
  @Schema(description = "")
  public String getUploadUrl() {
    return uploadUrl;
  }

  public void setUploadUrl(String uploadUrl) {
    this.uploadUrl = uploadUrl;
  }

  public Release url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   *
   * @return url
   **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Release zipballUrl(String zipballUrl) {
    this.zipballUrl = zipballUrl;
    return this;
  }

  /**
   * Get zipballUrl
   *
   * @return zipballUrl
   **/
  @Schema(description = "")
  public String getZipballUrl() {
    return zipballUrl;
  }

  public void setZipballUrl(String zipballUrl) {
    this.zipballUrl = zipballUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Release release = (Release) o;
    return Objects.equals(this.assets, release.assets) &&
           Objects.equals(this.author, release.author) &&
           Objects.equals(this.body, release.body) &&
           Objects.equals(this.createdAt, release.createdAt) &&
           Objects.equals(this.draft, release.draft) &&
           Objects.equals(this.htmlUrl, release.htmlUrl) &&
           Objects.equals(this.id, release.id) &&
           Objects.equals(this.name, release.name) &&
           Objects.equals(this.prerelease, release.prerelease) &&
           Objects.equals(this.publishedAt, release.publishedAt) &&
           Objects.equals(this.tagName, release.tagName) &&
           Objects.equals(this.tarballUrl, release.tarballUrl) &&
           Objects.equals(this.targetCommitish, release.targetCommitish) &&
           Objects.equals(this.uploadUrl, release.uploadUrl) &&
           Objects.equals(this.url, release.url) &&
           Objects.equals(this.zipballUrl, release.zipballUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assets, author, body, createdAt, draft, htmlUrl, id, name, prerelease, publishedAt, tagName, tarballUrl, targetCommitish, uploadUrl, url, zipballUrl);
  }


  @Override
  public String toString() {

    String sb = "class Release {\n" +
                "    assets: " + toIndentedString(assets) + "\n" +
                "    author: " + toIndentedString(author) + "\n" +
                "    body: " + toIndentedString(body) + "\n" +
                "    createdAt: " + toIndentedString(createdAt) + "\n" +
                "    draft: " + toIndentedString(draft) + "\n" +
                "    htmlUrl: " + toIndentedString(htmlUrl) + "\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    prerelease: " + toIndentedString(prerelease) + "\n" +
                "    publishedAt: " + toIndentedString(publishedAt) + "\n" +
                "    tagName: " + toIndentedString(tagName) + "\n" +
                "    tarballUrl: " + toIndentedString(tarballUrl) + "\n" +
                "    targetCommitish: " + toIndentedString(targetCommitish) + "\n" +
                "    uploadUrl: " + toIndentedString(uploadUrl) + "\n" +
                "    url: " + toIndentedString(url) + "\n" +
                "    zipballUrl: " + toIndentedString(zipballUrl) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
