/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * RenameUserOption options when renaming a user
 */
@Schema(description = "RenameUserOption options when renaming a user")
public class RenameUserOption {
  @SerializedName("new_username")
  private String newUsername;

  public RenameUserOption newUsername(String newUsername) {
    this.newUsername = newUsername;
    return this;
  }

  /**
   * New username for this user. This name cannot be in use yet by any other user.
   *
   * @return newUsername
   **/
  @Schema(required = true, description = "New username for this user. This name cannot be in use yet by any other user.")
  public String getNewUsername() {
    return newUsername;
  }

  public void setNewUsername(String newUsername) {
    this.newUsername = newUsername;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RenameUserOption renameUserOption = (RenameUserOption) o;
    return Objects.equals(this.newUsername, renameUserOption.newUsername);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newUsername);
  }


  @Override
  public String toString() {

    String sb = "class RenameUserOption {\n" +
                "    newUsername: " + toIndentedString(newUsername) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
