/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * RepoTopicOptions a collection of repo topic names
 */
@Schema(description = "RepoTopicOptions a collection of repo topic names")
public class RepoTopicOptions {
  @SerializedName("topics")
  private List<String> topics;

  public RepoTopicOptions topics(List<String> topics) {
    this.topics = topics;
    return this;
  }

  public RepoTopicOptions addTopicsItem(String topicsItem) {
    if (this.topics == null) {
      this.topics = new ArrayList<String>();
    }
    this.topics.add(topicsItem);
    return this;
  }

  /**
   * list of topic names
   *
   * @return topics
   **/
  @Schema(description = "list of topic names")
  public List<String> getTopics() {
    return topics;
  }

  public void setTopics(List<String> topics) {
    this.topics = topics;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepoTopicOptions repoTopicOptions = (RepoTopicOptions) o;
    return Objects.equals(this.topics, repoTopicOptions.topics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(topics);
  }


  @Override
  public String toString() {

    String sb = "class RepoTopicOptions {\n" +
                "    topics: " + toIndentedString(topics) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
