/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Repository represents a repository
 */
@Schema(description = "Repository represents a repository")
public class Repository {
  @SerializedName("allow_fast_forward_only_merge")
  private Boolean allowFastForwardOnlyMerge;

  @SerializedName("allow_merge_commits")
  private Boolean allowMergeCommits;

  @SerializedName("allow_rebase")
  private Boolean allowRebase;

  @SerializedName("allow_rebase_explicit")
  private Boolean allowRebaseExplicit;

  @SerializedName("allow_rebase_update")
  private Boolean allowRebaseUpdate;

  @SerializedName("allow_squash_merge")
  private Boolean allowSquashMerge;

  @SerializedName("archived")
  private Boolean archived;

  @SerializedName("archived_at")
  private OffsetDateTime archivedAt;

  @SerializedName("avatar_url")
  private String avatarUrl;

  @SerializedName("clone_url")
  private String cloneUrl;

  @SerializedName("created_at")
  private OffsetDateTime createdAt;

  @SerializedName("default_allow_maintainer_edit")
  private Boolean defaultAllowMaintainerEdit;

  @SerializedName("default_branch")
  private String defaultBranch;

  @SerializedName("default_delete_branch_after_merge")
  private Boolean defaultDeleteBranchAfterMerge;

  @SerializedName("default_merge_style")
  private String defaultMergeStyle;

  @SerializedName("description")
  private String description;

  @SerializedName("empty")
  private Boolean empty;

  @SerializedName("external_tracker")
  private ExternalTracker externalTracker;

  @SerializedName("external_wiki")
  private ExternalWiki externalWiki;

  @SerializedName("fork")
  private Boolean fork;

  @SerializedName("forks_count")
  private Long forksCount;

  @SerializedName("full_name")
  private String fullName;

  @SerializedName("has_actions")
  private Boolean hasActions;

  @SerializedName("has_issues")
  private Boolean hasIssues;

  @SerializedName("has_packages")
  private Boolean hasPackages;

  @SerializedName("has_projects")
  private Boolean hasProjects;

  @SerializedName("has_pull_requests")
  private Boolean hasPullRequests;

  @SerializedName("has_releases")
  private Boolean hasReleases;

  @SerializedName("has_wiki")
  private Boolean hasWiki;

  @SerializedName("html_url")
  private String htmlUrl;

  @SerializedName("id")
  private Long id;

  @SerializedName("ignore_whitespace_conflicts")
  private Boolean ignoreWhitespaceConflicts;

  @SerializedName("internal")
  private Boolean internal;

  @SerializedName("internal_tracker")
  private InternalTracker internalTracker;

  @SerializedName("language")
  private String language;

  @SerializedName("languages_url")
  private String languagesUrl;

  @SerializedName("licenses")
  private List<String> licenses;

  @SerializedName("link")
  private String link;

  @SerializedName("mirror")
  private Boolean mirror;

  @SerializedName("mirror_interval")
  private String mirrorInterval;

  @SerializedName("mirror_updated")
  private OffsetDateTime mirrorUpdated;

  @SerializedName("name")
  private String name;
  @SerializedName("object_format_name")
  private ObjectFormatNameEnum objectFormatName;
  @SerializedName("open_issues_count")
  private Long openIssuesCount;
  @SerializedName("open_pr_counter")
  private Long openPrCounter;
  @SerializedName("original_url")
  private String originalUrl;
  @SerializedName("owner")
  private User owner;
  @SerializedName("parent")
  private Repository parent;
  @SerializedName("permissions")
  private Permission permissions;
  @SerializedName("private")
  private Boolean _private;
  @SerializedName("projects_mode")
  private String projectsMode;
  @SerializedName("release_counter")
  private Long releaseCounter;
  @SerializedName("repo_transfer")
  private RepoTransfer repoTransfer;
  @SerializedName("size")
  private Long size;
  @SerializedName("ssh_url")
  private String sshUrl;
  @SerializedName("stars_count")
  private Long starsCount;
  @SerializedName("template")
  private Boolean template;
  @SerializedName("topics")
  private List<String> topics;
  @SerializedName("updated_at")
  private OffsetDateTime updatedAt;
  @SerializedName("url")
  private String url;
  @SerializedName("watchers_count")
  private Long watchersCount;
  @SerializedName("website")
  private String website;

  /**
   * ObjectFormatName of the underlying git repository
   */
  @JsonAdapter(ObjectFormatNameEnum.Adapter.class)
  public enum ObjectFormatNameEnum {
    @SerializedName("sha1")
    SHA1("sha1"),
    @SerializedName("sha256")
    SHA256("sha256");

    private final String value;

    ObjectFormatNameEnum(String value) {
      this.value = value;
    }

    public static class Adapter extends TypeAdapter<ObjectFormatNameEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ObjectFormatNameEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public ObjectFormatNameEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return ObjectFormatNameEnum.fromValue((String) (value));
      }
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ObjectFormatNameEnum fromValue(String input) {
      for (ObjectFormatNameEnum b : ObjectFormatNameEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
  }

  public Repository allowFastForwardOnlyMerge(Boolean allowFastForwardOnlyMerge) {
    this.allowFastForwardOnlyMerge = allowFastForwardOnlyMerge;
    return this;
  }

  /**
   * Get allowFastForwardOnlyMerge
   *
   * @return allowFastForwardOnlyMerge
   **/
  @Schema(description = "")
  public Boolean isAllowFastForwardOnlyMerge() {
    return allowFastForwardOnlyMerge;
  }

  public void setAllowFastForwardOnlyMerge(Boolean allowFastForwardOnlyMerge) {
    this.allowFastForwardOnlyMerge = allowFastForwardOnlyMerge;
  }

  public Repository allowMergeCommits(Boolean allowMergeCommits) {
    this.allowMergeCommits = allowMergeCommits;
    return this;
  }

  /**
   * Get allowMergeCommits
   *
   * @return allowMergeCommits
   **/
  @Schema(description = "")
  public Boolean isAllowMergeCommits() {
    return allowMergeCommits;
  }

  public void setAllowMergeCommits(Boolean allowMergeCommits) {
    this.allowMergeCommits = allowMergeCommits;
  }

  public Repository allowRebase(Boolean allowRebase) {
    this.allowRebase = allowRebase;
    return this;
  }

  /**
   * Get allowRebase
   *
   * @return allowRebase
   **/
  @Schema(description = "")
  public Boolean isAllowRebase() {
    return allowRebase;
  }

  public void setAllowRebase(Boolean allowRebase) {
    this.allowRebase = allowRebase;
  }

  public Repository allowRebaseExplicit(Boolean allowRebaseExplicit) {
    this.allowRebaseExplicit = allowRebaseExplicit;
    return this;
  }

  /**
   * Get allowRebaseExplicit
   *
   * @return allowRebaseExplicit
   **/
  @Schema(description = "")
  public Boolean isAllowRebaseExplicit() {
    return allowRebaseExplicit;
  }

  public void setAllowRebaseExplicit(Boolean allowRebaseExplicit) {
    this.allowRebaseExplicit = allowRebaseExplicit;
  }

  public Repository allowRebaseUpdate(Boolean allowRebaseUpdate) {
    this.allowRebaseUpdate = allowRebaseUpdate;
    return this;
  }

  /**
   * Get allowRebaseUpdate
   *
   * @return allowRebaseUpdate
   **/
  @Schema(description = "")
  public Boolean isAllowRebaseUpdate() {
    return allowRebaseUpdate;
  }

  public void setAllowRebaseUpdate(Boolean allowRebaseUpdate) {
    this.allowRebaseUpdate = allowRebaseUpdate;
  }

  public Repository allowSquashMerge(Boolean allowSquashMerge) {
    this.allowSquashMerge = allowSquashMerge;
    return this;
  }

  /**
   * Get allowSquashMerge
   *
   * @return allowSquashMerge
   **/
  @Schema(description = "")
  public Boolean isAllowSquashMerge() {
    return allowSquashMerge;
  }

  public void setAllowSquashMerge(Boolean allowSquashMerge) {
    this.allowSquashMerge = allowSquashMerge;
  }

  public Repository archived(Boolean archived) {
    this.archived = archived;
    return this;
  }

  /**
   * Get archived
   *
   * @return archived
   **/
  @Schema(description = "")
  public Boolean isArchived() {
    return archived;
  }

  public void setArchived(Boolean archived) {
    this.archived = archived;
  }

  public Repository archivedAt(OffsetDateTime archivedAt) {
    this.archivedAt = archivedAt;
    return this;
  }

  /**
   * Get archivedAt
   *
   * @return archivedAt
   **/
  @Schema(description = "")
  public OffsetDateTime getArchivedAt() {
    return archivedAt;
  }

  public void setArchivedAt(OffsetDateTime archivedAt) {
    this.archivedAt = archivedAt;
  }

  public Repository avatarUrl(String avatarUrl) {
    this.avatarUrl = avatarUrl;
    return this;
  }

  /**
   * Get avatarUrl
   *
   * @return avatarUrl
   **/
  @Schema(description = "")
  public String getAvatarUrl() {
    return avatarUrl;
  }

  public void setAvatarUrl(String avatarUrl) {
    this.avatarUrl = avatarUrl;
  }

  public Repository cloneUrl(String cloneUrl) {
    this.cloneUrl = cloneUrl;
    return this;
  }

  /**
   * Get cloneUrl
   *
   * @return cloneUrl
   **/
  @Schema(description = "")
  public String getCloneUrl() {
    return cloneUrl;
  }

  public void setCloneUrl(String cloneUrl) {
    this.cloneUrl = cloneUrl;
  }

  public Repository createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   *
   * @return createdAt
   **/
  @Schema(description = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public Repository defaultAllowMaintainerEdit(Boolean defaultAllowMaintainerEdit) {
    this.defaultAllowMaintainerEdit = defaultAllowMaintainerEdit;
    return this;
  }

  /**
   * Get defaultAllowMaintainerEdit
   *
   * @return defaultAllowMaintainerEdit
   **/
  @Schema(description = "")
  public Boolean isDefaultAllowMaintainerEdit() {
    return defaultAllowMaintainerEdit;
  }

  public void setDefaultAllowMaintainerEdit(Boolean defaultAllowMaintainerEdit) {
    this.defaultAllowMaintainerEdit = defaultAllowMaintainerEdit;
  }

  public Repository defaultBranch(String defaultBranch) {
    this.defaultBranch = defaultBranch;
    return this;
  }

  /**
   * Get defaultBranch
   *
   * @return defaultBranch
   **/
  @Schema(description = "")
  public String getDefaultBranch() {
    return defaultBranch;
  }

  public void setDefaultBranch(String defaultBranch) {
    this.defaultBranch = defaultBranch;
  }

  public Repository defaultDeleteBranchAfterMerge(Boolean defaultDeleteBranchAfterMerge) {
    this.defaultDeleteBranchAfterMerge = defaultDeleteBranchAfterMerge;
    return this;
  }

  /**
   * Get defaultDeleteBranchAfterMerge
   *
   * @return defaultDeleteBranchAfterMerge
   **/
  @Schema(description = "")
  public Boolean isDefaultDeleteBranchAfterMerge() {
    return defaultDeleteBranchAfterMerge;
  }

  public void setDefaultDeleteBranchAfterMerge(Boolean defaultDeleteBranchAfterMerge) {
    this.defaultDeleteBranchAfterMerge = defaultDeleteBranchAfterMerge;
  }

  public Repository defaultMergeStyle(String defaultMergeStyle) {
    this.defaultMergeStyle = defaultMergeStyle;
    return this;
  }

  /**
   * Get defaultMergeStyle
   *
   * @return defaultMergeStyle
   **/
  @Schema(description = "")
  public String getDefaultMergeStyle() {
    return defaultMergeStyle;
  }

  public void setDefaultMergeStyle(String defaultMergeStyle) {
    this.defaultMergeStyle = defaultMergeStyle;
  }

  public Repository description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   *
   * @return description
   **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Repository empty(Boolean empty) {
    this.empty = empty;
    return this;
  }

  /**
   * Get empty
   *
   * @return empty
   **/
  @Schema(description = "")
  public Boolean isEmpty() {
    return empty;
  }

  public void setEmpty(Boolean empty) {
    this.empty = empty;
  }

  public Repository externalTracker(ExternalTracker externalTracker) {
    this.externalTracker = externalTracker;
    return this;
  }

  /**
   * Get externalTracker
   *
   * @return externalTracker
   **/
  @Schema(description = "")
  public ExternalTracker getExternalTracker() {
    return externalTracker;
  }

  public void setExternalTracker(ExternalTracker externalTracker) {
    this.externalTracker = externalTracker;
  }

  public Repository externalWiki(ExternalWiki externalWiki) {
    this.externalWiki = externalWiki;
    return this;
  }

  /**
   * Get externalWiki
   *
   * @return externalWiki
   **/
  @Schema(description = "")
  public ExternalWiki getExternalWiki() {
    return externalWiki;
  }

  public void setExternalWiki(ExternalWiki externalWiki) {
    this.externalWiki = externalWiki;
  }

  public Repository fork(Boolean fork) {
    this.fork = fork;
    return this;
  }

  /**
   * Get fork
   *
   * @return fork
   **/
  @Schema(description = "")
  public Boolean isFork() {
    return fork;
  }

  public void setFork(Boolean fork) {
    this.fork = fork;
  }

  public Repository forksCount(Long forksCount) {
    this.forksCount = forksCount;
    return this;
  }

  /**
   * Get forksCount
   *
   * @return forksCount
   **/
  @Schema(description = "")
  public Long getForksCount() {
    return forksCount;
  }

  public void setForksCount(Long forksCount) {
    this.forksCount = forksCount;
  }

  public Repository fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

  /**
   * Get fullName
   *
   * @return fullName
   **/
  @Schema(description = "")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public Repository hasActions(Boolean hasActions) {
    this.hasActions = hasActions;
    return this;
  }

  /**
   * Get hasActions
   *
   * @return hasActions
   **/
  @Schema(description = "")
  public Boolean isHasActions() {
    return hasActions;
  }

  public void setHasActions(Boolean hasActions) {
    this.hasActions = hasActions;
  }

  public Repository hasIssues(Boolean hasIssues) {
    this.hasIssues = hasIssues;
    return this;
  }

  /**
   * Get hasIssues
   *
   * @return hasIssues
   **/
  @Schema(description = "")
  public Boolean isHasIssues() {
    return hasIssues;
  }

  public void setHasIssues(Boolean hasIssues) {
    this.hasIssues = hasIssues;
  }

  public Repository hasPackages(Boolean hasPackages) {
    this.hasPackages = hasPackages;
    return this;
  }

  /**
   * Get hasPackages
   *
   * @return hasPackages
   **/
  @Schema(description = "")
  public Boolean isHasPackages() {
    return hasPackages;
  }

  public void setHasPackages(Boolean hasPackages) {
    this.hasPackages = hasPackages;
  }

  public Repository hasProjects(Boolean hasProjects) {
    this.hasProjects = hasProjects;
    return this;
  }

  /**
   * Get hasProjects
   *
   * @return hasProjects
   **/
  @Schema(description = "")
  public Boolean isHasProjects() {
    return hasProjects;
  }

  public void setHasProjects(Boolean hasProjects) {
    this.hasProjects = hasProjects;
  }

  public Repository hasPullRequests(Boolean hasPullRequests) {
    this.hasPullRequests = hasPullRequests;
    return this;
  }

  /**
   * Get hasPullRequests
   *
   * @return hasPullRequests
   **/
  @Schema(description = "")
  public Boolean isHasPullRequests() {
    return hasPullRequests;
  }

  public void setHasPullRequests(Boolean hasPullRequests) {
    this.hasPullRequests = hasPullRequests;
  }

  public Repository hasReleases(Boolean hasReleases) {
    this.hasReleases = hasReleases;
    return this;
  }

  /**
   * Get hasReleases
   *
   * @return hasReleases
   **/
  @Schema(description = "")
  public Boolean isHasReleases() {
    return hasReleases;
  }

  public void setHasReleases(Boolean hasReleases) {
    this.hasReleases = hasReleases;
  }

  public Repository hasWiki(Boolean hasWiki) {
    this.hasWiki = hasWiki;
    return this;
  }

  /**
   * Get hasWiki
   *
   * @return hasWiki
   **/
  @Schema(description = "")
  public Boolean isHasWiki() {
    return hasWiki;
  }

  public void setHasWiki(Boolean hasWiki) {
    this.hasWiki = hasWiki;
  }

  public Repository htmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
    return this;
  }

  /**
   * Get htmlUrl
   *
   * @return htmlUrl
   **/
  @Schema(description = "")
  public String getHtmlUrl() {
    return htmlUrl;
  }

  public void setHtmlUrl(String htmlUrl) {
    this.htmlUrl = htmlUrl;
  }

  public Repository id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Repository ignoreWhitespaceConflicts(Boolean ignoreWhitespaceConflicts) {
    this.ignoreWhitespaceConflicts = ignoreWhitespaceConflicts;
    return this;
  }

  /**
   * Get ignoreWhitespaceConflicts
   *
   * @return ignoreWhitespaceConflicts
   **/
  @Schema(description = "")
  public Boolean isIgnoreWhitespaceConflicts() {
    return ignoreWhitespaceConflicts;
  }

  public void setIgnoreWhitespaceConflicts(Boolean ignoreWhitespaceConflicts) {
    this.ignoreWhitespaceConflicts = ignoreWhitespaceConflicts;
  }

  public Repository internal(Boolean internal) {
    this.internal = internal;
    return this;
  }

  /**
   * Get internal
   *
   * @return internal
   **/
  @Schema(description = "")
  public Boolean isInternal() {
    return internal;
  }

  public void setInternal(Boolean internal) {
    this.internal = internal;
  }

  public Repository internalTracker(InternalTracker internalTracker) {
    this.internalTracker = internalTracker;
    return this;
  }

  /**
   * Get internalTracker
   *
   * @return internalTracker
   **/
  @Schema(description = "")
  public InternalTracker getInternalTracker() {
    return internalTracker;
  }

  public void setInternalTracker(InternalTracker internalTracker) {
    this.internalTracker = internalTracker;
  }

  public Repository language(String language) {
    this.language = language;
    return this;
  }

  /**
   * Get language
   *
   * @return language
   **/
  @Schema(description = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public Repository languagesUrl(String languagesUrl) {
    this.languagesUrl = languagesUrl;
    return this;
  }

  /**
   * Get languagesUrl
   *
   * @return languagesUrl
   **/
  @Schema(description = "")
  public String getLanguagesUrl() {
    return languagesUrl;
  }

  public void setLanguagesUrl(String languagesUrl) {
    this.languagesUrl = languagesUrl;
  }

  public Repository licenses(List<String> licenses) {
    this.licenses = licenses;
    return this;
  }

  public Repository addLicensesItem(String licensesItem) {
    if (this.licenses == null) {
      this.licenses = new ArrayList<String>();
    }
    this.licenses.add(licensesItem);
    return this;
  }

  /**
   * Get licenses
   *
   * @return licenses
   **/
  @Schema(description = "")
  public List<String> getLicenses() {
    return licenses;
  }

  public void setLicenses(List<String> licenses) {
    this.licenses = licenses;
  }

  public Repository link(String link) {
    this.link = link;
    return this;
  }

  /**
   * Get link
   *
   * @return link
   **/
  @Schema(description = "")
  public String getLink() {
    return link;
  }

  public void setLink(String link) {
    this.link = link;
  }

  public Repository mirror(Boolean mirror) {
    this.mirror = mirror;
    return this;
  }

  /**
   * Get mirror
   *
   * @return mirror
   **/
  @Schema(description = "")
  public Boolean isMirror() {
    return mirror;
  }

  public void setMirror(Boolean mirror) {
    this.mirror = mirror;
  }

  public Repository mirrorInterval(String mirrorInterval) {
    this.mirrorInterval = mirrorInterval;
    return this;
  }

  /**
   * Get mirrorInterval
   *
   * @return mirrorInterval
   **/
  @Schema(description = "")
  public String getMirrorInterval() {
    return mirrorInterval;
  }

  public void setMirrorInterval(String mirrorInterval) {
    this.mirrorInterval = mirrorInterval;
  }

  public Repository mirrorUpdated(OffsetDateTime mirrorUpdated) {
    this.mirrorUpdated = mirrorUpdated;
    return this;
  }

  /**
   * Get mirrorUpdated
   *
   * @return mirrorUpdated
   **/
  @Schema(description = "")
  public OffsetDateTime getMirrorUpdated() {
    return mirrorUpdated;
  }

  public void setMirrorUpdated(OffsetDateTime mirrorUpdated) {
    this.mirrorUpdated = mirrorUpdated;
  }

  public Repository name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Repository objectFormatName(ObjectFormatNameEnum objectFormatName) {
    this.objectFormatName = objectFormatName;
    return this;
  }

  /**
   * ObjectFormatName of the underlying git repository
   *
   * @return objectFormatName
   **/
  @Schema(description = "ObjectFormatName of the underlying git repository")
  public ObjectFormatNameEnum getObjectFormatName() {
    return objectFormatName;
  }

  public void setObjectFormatName(ObjectFormatNameEnum objectFormatName) {
    this.objectFormatName = objectFormatName;
  }

  public Repository openIssuesCount(Long openIssuesCount) {
    this.openIssuesCount = openIssuesCount;
    return this;
  }

  /**
   * Get openIssuesCount
   *
   * @return openIssuesCount
   **/
  @Schema(description = "")
  public Long getOpenIssuesCount() {
    return openIssuesCount;
  }

  public void setOpenIssuesCount(Long openIssuesCount) {
    this.openIssuesCount = openIssuesCount;
  }

  public Repository openPrCounter(Long openPrCounter) {
    this.openPrCounter = openPrCounter;
    return this;
  }

  /**
   * Get openPrCounter
   *
   * @return openPrCounter
   **/
  @Schema(description = "")
  public Long getOpenPrCounter() {
    return openPrCounter;
  }

  public void setOpenPrCounter(Long openPrCounter) {
    this.openPrCounter = openPrCounter;
  }

  public Repository originalUrl(String originalUrl) {
    this.originalUrl = originalUrl;
    return this;
  }

  /**
   * Get originalUrl
   *
   * @return originalUrl
   **/
  @Schema(description = "")
  public String getOriginalUrl() {
    return originalUrl;
  }

  public void setOriginalUrl(String originalUrl) {
    this.originalUrl = originalUrl;
  }

  public Repository owner(User owner) {
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   *
   * @return owner
   **/
  @Schema(description = "")
  public User getOwner() {
    return owner;
  }

  public void setOwner(User owner) {
    this.owner = owner;
  }

  public Repository parent(Repository parent) {
    this.parent = parent;
    return this;
  }

  /**
   * Get parent
   *
   * @return parent
   **/
  @Schema(description = "")
  public Repository getParent() {
    return parent;
  }

  public void setParent(Repository parent) {
    this.parent = parent;
  }

  public Repository permissions(Permission permissions) {
    this.permissions = permissions;
    return this;
  }

  /**
   * Get permissions
   *
   * @return permissions
   **/
  @Schema(description = "")
  public Permission getPermissions() {
    return permissions;
  }

  public void setPermissions(Permission permissions) {
    this.permissions = permissions;
  }

  public Repository _private(Boolean _private) {
    this._private = _private;
    return this;
  }

  /**
   * Get _private
   *
   * @return _private
   **/
  @Schema(description = "")
  public Boolean isPrivate() {
    return _private;
  }

  public void setPrivate(Boolean _private) {
    this._private = _private;
  }

  public Repository projectsMode(String projectsMode) {
    this.projectsMode = projectsMode;
    return this;
  }

  /**
   * Get projectsMode
   *
   * @return projectsMode
   **/
  @Schema(description = "")
  public String getProjectsMode() {
    return projectsMode;
  }

  public void setProjectsMode(String projectsMode) {
    this.projectsMode = projectsMode;
  }

  public Repository releaseCounter(Long releaseCounter) {
    this.releaseCounter = releaseCounter;
    return this;
  }

  /**
   * Get releaseCounter
   *
   * @return releaseCounter
   **/
  @Schema(description = "")
  public Long getReleaseCounter() {
    return releaseCounter;
  }

  public void setReleaseCounter(Long releaseCounter) {
    this.releaseCounter = releaseCounter;
  }

  public Repository repoTransfer(RepoTransfer repoTransfer) {
    this.repoTransfer = repoTransfer;
    return this;
  }

  /**
   * Get repoTransfer
   *
   * @return repoTransfer
   **/
  @Schema(description = "")
  public RepoTransfer getRepoTransfer() {
    return repoTransfer;
  }

  public void setRepoTransfer(RepoTransfer repoTransfer) {
    this.repoTransfer = repoTransfer;
  }

  public Repository size(Long size) {
    this.size = size;
    return this;
  }

  /**
   * Get size
   *
   * @return size
   **/
  @Schema(description = "")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public Repository sshUrl(String sshUrl) {
    this.sshUrl = sshUrl;
    return this;
  }

  /**
   * Get sshUrl
   *
   * @return sshUrl
   **/
  @Schema(description = "")
  public String getSshUrl() {
    return sshUrl;
  }

  public void setSshUrl(String sshUrl) {
    this.sshUrl = sshUrl;
  }

  public Repository starsCount(Long starsCount) {
    this.starsCount = starsCount;
    return this;
  }

  /**
   * Get starsCount
   *
   * @return starsCount
   **/
  @Schema(description = "")
  public Long getStarsCount() {
    return starsCount;
  }

  public void setStarsCount(Long starsCount) {
    this.starsCount = starsCount;
  }

  public Repository template(Boolean template) {
    this.template = template;
    return this;
  }

  /**
   * Get template
   *
   * @return template
   **/
  @Schema(description = "")
  public Boolean isTemplate() {
    return template;
  }

  public void setTemplate(Boolean template) {
    this.template = template;
  }

  public Repository topics(List<String> topics) {
    this.topics = topics;
    return this;
  }

  public Repository addTopicsItem(String topicsItem) {
    if (this.topics == null) {
      this.topics = new ArrayList<String>();
    }
    this.topics.add(topicsItem);
    return this;
  }

  /**
   * Get topics
   *
   * @return topics
   **/
  @Schema(description = "")
  public List<String> getTopics() {
    return topics;
  }

  public void setTopics(List<String> topics) {
    this.topics = topics;
  }

  public Repository updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   *
   * @return updatedAt
   **/
  @Schema(description = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public Repository url(String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   *
   * @return url
   **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Repository watchersCount(Long watchersCount) {
    this.watchersCount = watchersCount;
    return this;
  }

  /**
   * Get watchersCount
   *
   * @return watchersCount
   **/
  @Schema(description = "")
  public Long getWatchersCount() {
    return watchersCount;
  }

  public void setWatchersCount(Long watchersCount) {
    this.watchersCount = watchersCount;
  }

  public Repository website(String website) {
    this.website = website;
    return this;
  }

  /**
   * Get website
   *
   * @return website
   **/
  @Schema(description = "")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Repository repository = (Repository) o;
    return Objects.equals(this.allowFastForwardOnlyMerge, repository.allowFastForwardOnlyMerge) &&
           Objects.equals(this.allowMergeCommits, repository.allowMergeCommits) &&
           Objects.equals(this.allowRebase, repository.allowRebase) &&
           Objects.equals(this.allowRebaseExplicit, repository.allowRebaseExplicit) &&
           Objects.equals(this.allowRebaseUpdate, repository.allowRebaseUpdate) &&
           Objects.equals(this.allowSquashMerge, repository.allowSquashMerge) &&
           Objects.equals(this.archived, repository.archived) &&
           Objects.equals(this.archivedAt, repository.archivedAt) &&
           Objects.equals(this.avatarUrl, repository.avatarUrl) &&
           Objects.equals(this.cloneUrl, repository.cloneUrl) &&
           Objects.equals(this.createdAt, repository.createdAt) &&
           Objects.equals(this.defaultAllowMaintainerEdit, repository.defaultAllowMaintainerEdit) &&
           Objects.equals(this.defaultBranch, repository.defaultBranch) &&
           Objects.equals(this.defaultDeleteBranchAfterMerge, repository.defaultDeleteBranchAfterMerge) &&
           Objects.equals(this.defaultMergeStyle, repository.defaultMergeStyle) &&
           Objects.equals(this.description, repository.description) &&
           Objects.equals(this.empty, repository.empty) &&
           Objects.equals(this.externalTracker, repository.externalTracker) &&
           Objects.equals(this.externalWiki, repository.externalWiki) &&
           Objects.equals(this.fork, repository.fork) &&
           Objects.equals(this.forksCount, repository.forksCount) &&
           Objects.equals(this.fullName, repository.fullName) &&
           Objects.equals(this.hasActions, repository.hasActions) &&
           Objects.equals(this.hasIssues, repository.hasIssues) &&
           Objects.equals(this.hasPackages, repository.hasPackages) &&
           Objects.equals(this.hasProjects, repository.hasProjects) &&
           Objects.equals(this.hasPullRequests, repository.hasPullRequests) &&
           Objects.equals(this.hasReleases, repository.hasReleases) &&
           Objects.equals(this.hasWiki, repository.hasWiki) &&
           Objects.equals(this.htmlUrl, repository.htmlUrl) &&
           Objects.equals(this.id, repository.id) &&
           Objects.equals(this.ignoreWhitespaceConflicts, repository.ignoreWhitespaceConflicts) &&
           Objects.equals(this.internal, repository.internal) &&
           Objects.equals(this.internalTracker, repository.internalTracker) &&
           Objects.equals(this.language, repository.language) &&
           Objects.equals(this.languagesUrl, repository.languagesUrl) &&
           Objects.equals(this.licenses, repository.licenses) &&
           Objects.equals(this.link, repository.link) &&
           Objects.equals(this.mirror, repository.mirror) &&
           Objects.equals(this.mirrorInterval, repository.mirrorInterval) &&
           Objects.equals(this.mirrorUpdated, repository.mirrorUpdated) &&
           Objects.equals(this.name, repository.name) &&
           this.objectFormatName == repository.objectFormatName &&
           Objects.equals(this.openIssuesCount, repository.openIssuesCount) &&
           Objects.equals(this.openPrCounter, repository.openPrCounter) &&
           Objects.equals(this.originalUrl, repository.originalUrl) &&
           Objects.equals(this.owner, repository.owner) &&
           Objects.equals(this.parent, repository.parent) &&
           Objects.equals(this.permissions, repository.permissions) &&
           Objects.equals(this._private, repository._private) &&
           Objects.equals(this.projectsMode, repository.projectsMode) &&
           Objects.equals(this.releaseCounter, repository.releaseCounter) &&
           Objects.equals(this.repoTransfer, repository.repoTransfer) &&
           Objects.equals(this.size, repository.size) &&
           Objects.equals(this.sshUrl, repository.sshUrl) &&
           Objects.equals(this.starsCount, repository.starsCount) &&
           Objects.equals(this.template, repository.template) &&
           Objects.equals(this.topics, repository.topics) &&
           Objects.equals(this.updatedAt, repository.updatedAt) &&
           Objects.equals(this.url, repository.url) &&
           Objects.equals(this.watchersCount, repository.watchersCount) &&
           Objects.equals(this.website, repository.website);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowFastForwardOnlyMerge, allowMergeCommits, allowRebase, allowRebaseExplicit, allowRebaseUpdate, allowSquashMerge, archived, archivedAt, avatarUrl, cloneUrl, createdAt, defaultAllowMaintainerEdit, defaultBranch, defaultDeleteBranchAfterMerge, defaultMergeStyle, description, empty, externalTracker, externalWiki, fork, forksCount, fullName, hasActions, hasIssues, hasPackages, hasProjects, hasPullRequests, hasReleases, hasWiki, htmlUrl, id, ignoreWhitespaceConflicts, internal, internalTracker, language, languagesUrl, licenses, link, mirror, mirrorInterval, mirrorUpdated, name, objectFormatName, openIssuesCount, openPrCounter, originalUrl, owner, parent, permissions, _private, projectsMode, releaseCounter, repoTransfer, size, sshUrl, starsCount, template, topics, updatedAt, url, watchersCount, website);
  }


  @Override
  public String toString() {

    String sb = "class Repository {\n" +
                "    allowFastForwardOnlyMerge: " + toIndentedString(allowFastForwardOnlyMerge) + "\n" +
                "    allowMergeCommits: " + toIndentedString(allowMergeCommits) + "\n" +
                "    allowRebase: " + toIndentedString(allowRebase) + "\n" +
                "    allowRebaseExplicit: " + toIndentedString(allowRebaseExplicit) + "\n" +
                "    allowRebaseUpdate: " + toIndentedString(allowRebaseUpdate) + "\n" +
                "    allowSquashMerge: " + toIndentedString(allowSquashMerge) + "\n" +
                "    archived: " + toIndentedString(archived) + "\n" +
                "    archivedAt: " + toIndentedString(archivedAt) + "\n" +
                "    avatarUrl: " + toIndentedString(avatarUrl) + "\n" +
                "    cloneUrl: " + toIndentedString(cloneUrl) + "\n" +
                "    createdAt: " + toIndentedString(createdAt) + "\n" +
                "    defaultAllowMaintainerEdit: " + toIndentedString(defaultAllowMaintainerEdit) + "\n" +
                "    defaultBranch: " + toIndentedString(defaultBranch) + "\n" +
                "    defaultDeleteBranchAfterMerge: " + toIndentedString(defaultDeleteBranchAfterMerge) + "\n" +
                "    defaultMergeStyle: " + toIndentedString(defaultMergeStyle) + "\n" +
                "    description: " + toIndentedString(description) + "\n" +
                "    empty: " + toIndentedString(empty) + "\n" +
                "    externalTracker: " + toIndentedString(externalTracker) + "\n" +
                "    externalWiki: " + toIndentedString(externalWiki) + "\n" +
                "    fork: " + toIndentedString(fork) + "\n" +
                "    forksCount: " + toIndentedString(forksCount) + "\n" +
                "    fullName: " + toIndentedString(fullName) + "\n" +
                "    hasActions: " + toIndentedString(hasActions) + "\n" +
                "    hasIssues: " + toIndentedString(hasIssues) + "\n" +
                "    hasPackages: " + toIndentedString(hasPackages) + "\n" +
                "    hasProjects: " + toIndentedString(hasProjects) + "\n" +
                "    hasPullRequests: " + toIndentedString(hasPullRequests) + "\n" +
                "    hasReleases: " + toIndentedString(hasReleases) + "\n" +
                "    hasWiki: " + toIndentedString(hasWiki) + "\n" +
                "    htmlUrl: " + toIndentedString(htmlUrl) + "\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    ignoreWhitespaceConflicts: " + toIndentedString(ignoreWhitespaceConflicts) + "\n" +
                "    internal: " + toIndentedString(internal) + "\n" +
                "    internalTracker: " + toIndentedString(internalTracker) + "\n" +
                "    language: " + toIndentedString(language) + "\n" +
                "    languagesUrl: " + toIndentedString(languagesUrl) + "\n" +
                "    licenses: " + toIndentedString(licenses) + "\n" +
                "    link: " + toIndentedString(link) + "\n" +
                "    mirror: " + toIndentedString(mirror) + "\n" +
                "    mirrorInterval: " + toIndentedString(mirrorInterval) + "\n" +
                "    mirrorUpdated: " + toIndentedString(mirrorUpdated) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    objectFormatName: " + toIndentedString(objectFormatName) + "\n" +
                "    openIssuesCount: " + toIndentedString(openIssuesCount) + "\n" +
                "    openPrCounter: " + toIndentedString(openPrCounter) + "\n" +
                "    originalUrl: " + toIndentedString(originalUrl) + "\n" +
                "    owner: " + toIndentedString(owner) + "\n" +
                "    parent: " + toIndentedString(parent) + "\n" +
                "    permissions: " + toIndentedString(permissions) + "\n" +
                "    _private: " + toIndentedString(_private) + "\n" +
                "    projectsMode: " + toIndentedString(projectsMode) + "\n" +
                "    releaseCounter: " + toIndentedString(releaseCounter) + "\n" +
                "    repoTransfer: " + toIndentedString(repoTransfer) + "\n" +
                "    size: " + toIndentedString(size) + "\n" +
                "    sshUrl: " + toIndentedString(sshUrl) + "\n" +
                "    starsCount: " + toIndentedString(starsCount) + "\n" +
                "    template: " + toIndentedString(template) + "\n" +
                "    topics: " + toIndentedString(topics) + "\n" +
                "    updatedAt: " + toIndentedString(updatedAt) + "\n" +
                "    url: " + toIndentedString(url) + "\n" +
                "    watchersCount: " + toIndentedString(watchersCount) + "\n" +
                "    website: " + toIndentedString(website) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
