/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Team represents a team in an organization
 */
@Schema(description = "Team represents a team in an organization")
public class Team {
  @SerializedName("can_create_org_repo")
  private Boolean canCreateOrgRepo;

  @SerializedName("description")
  private String description;

  @SerializedName("id")
  private Long id;

  @SerializedName("includes_all_repositories")
  private Boolean includesAllRepositories;

  @SerializedName("name")
  private String name;

  @SerializedName("organization")
  private Organization organization;
  @SerializedName("permission")
  private PermissionEnum permission;
  @SerializedName("units")
  private List<String> units;
  @SerializedName("units_map")
  private Map<String, String> unitsMap;

  /**
   * Gets or Sets permission
   */
  @JsonAdapter(PermissionEnum.Adapter.class)
  public enum PermissionEnum {
    @SerializedName("none")
    NONE("none"),
    @SerializedName("read")
    READ("read"),
    @SerializedName("write")
    WRITE("write"),
    @SerializedName("admin")
    ADMIN("admin"),
    @SerializedName("owner")
    OWNER("owner");

    private final String value;

    PermissionEnum(String value) {
      this.value = value;
    }

    public static class Adapter extends TypeAdapter<PermissionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PermissionEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public PermissionEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return PermissionEnum.fromValue((String) (value));
      }
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PermissionEnum fromValue(String input) {
      for (PermissionEnum b : PermissionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
  }

  public Team canCreateOrgRepo(Boolean canCreateOrgRepo) {
    this.canCreateOrgRepo = canCreateOrgRepo;
    return this;
  }

  /**
   * Get canCreateOrgRepo
   *
   * @return canCreateOrgRepo
   **/
  @Schema(description = "")
  public Boolean isCanCreateOrgRepo() {
    return canCreateOrgRepo;
  }

  public void setCanCreateOrgRepo(Boolean canCreateOrgRepo) {
    this.canCreateOrgRepo = canCreateOrgRepo;
  }

  public Team description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   *
   * @return description
   **/
  @Schema(description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Team id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Team includesAllRepositories(Boolean includesAllRepositories) {
    this.includesAllRepositories = includesAllRepositories;
    return this;
  }

  /**
   * Get includesAllRepositories
   *
   * @return includesAllRepositories
   **/
  @Schema(description = "")
  public Boolean isIncludesAllRepositories() {
    return includesAllRepositories;
  }

  public void setIncludesAllRepositories(Boolean includesAllRepositories) {
    this.includesAllRepositories = includesAllRepositories;
  }

  public Team name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Team organization(Organization organization) {
    this.organization = organization;
    return this;
  }

  /**
   * Get organization
   *
   * @return organization
   **/
  @Schema(description = "")
  public Organization getOrganization() {
    return organization;
  }

  public void setOrganization(Organization organization) {
    this.organization = organization;
  }

  public Team permission(PermissionEnum permission) {
    this.permission = permission;
    return this;
  }

  /**
   * Get permission
   *
   * @return permission
   **/
  @Schema(description = "")
  public PermissionEnum getPermission() {
    return permission;
  }

  public void setPermission(PermissionEnum permission) {
    this.permission = permission;
  }

  public Team units(List<String> units) {
    this.units = units;
    return this;
  }

  public Team addUnitsItem(String unitsItem) {
    if (this.units == null) {
      this.units = new ArrayList<String>();
    }
    this.units.add(unitsItem);
    return this;
  }

  /**
   * Get units
   *
   * @return units
   **/
  @Schema(example = "[\"repo.code\",\"repo.issues\",\"repo.ext_issues\",\"repo.wiki\",\"repo.pulls\",\"repo.releases\",\"repo.projects\",\"repo.ext_wiki\"]", description = "")
  public List<String> getUnits() {
    return units;
  }

  public void setUnits(List<String> units) {
    this.units = units;
  }

  public Team unitsMap(Map<String, String> unitsMap) {
    this.unitsMap = unitsMap;
    return this;
  }

  public Team putUnitsMapItem(String key, String unitsMapItem) {
    if (this.unitsMap == null) {
      this.unitsMap = new HashMap<String, String>();
    }
    this.unitsMap.put(key, unitsMapItem);
    return this;
  }

  /**
   * Get unitsMap
   *
   * @return unitsMap
   **/
  @Schema(example = "{\"repo.code\":\"read\",\"repo.ext_issues\":\"none\",\"repo.ext_wiki\":\"none\",\"repo.issues\":\"write\",\"repo.projects\":\"none\",\"repo.pulls\":\"owner\",\"repo.releases\":\"none\",\"repo.wiki\":\"admin\"}", description = "")
  public Map<String, String> getUnitsMap() {
    return unitsMap;
  }

  public void setUnitsMap(Map<String, String> unitsMap) {
    this.unitsMap = unitsMap;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Team team = (Team) o;
    return Objects.equals(this.canCreateOrgRepo, team.canCreateOrgRepo) &&
           Objects.equals(this.description, team.description) &&
           Objects.equals(this.id, team.id) &&
           Objects.equals(this.includesAllRepositories, team.includesAllRepositories) &&
           Objects.equals(this.name, team.name) &&
           Objects.equals(this.organization, team.organization) &&
           this.permission == team.permission &&
           Objects.equals(this.units, team.units) &&
           Objects.equals(this.unitsMap, team.unitsMap);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canCreateOrgRepo, description, id, includesAllRepositories, name, organization, permission, units, unitsMap);
  }


  @Override
  public String toString() {

    String sb = "class Team {\n" +
                "    canCreateOrgRepo: " + toIndentedString(canCreateOrgRepo) + "\n" +
                "    description: " + toIndentedString(description) + "\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    includesAllRepositories: " + toIndentedString(includesAllRepositories) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    organization: " + toIndentedString(organization) + "\n" +
                "    permission: " + toIndentedString(permission) + "\n" +
                "    units: " + toIndentedString(units) + "\n" +
                "    unitsMap: " + toIndentedString(unitsMap) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
