/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * TrackedTime worked time for an issue / pr
 */
@Schema(description = "TrackedTime worked time for an issue / pr")
public class TrackedTime {
  @SerializedName("created")
  private OffsetDateTime created;

  @SerializedName("id")
  private Long id;

  @SerializedName("issue")
  private Issue issue;

  @SerializedName("issue_id")
  private Long issueId;

  @SerializedName("time")
  private Long time;

  @SerializedName("user_id")
  private Long userId;

  @SerializedName("user_name")
  private String userName;

  public TrackedTime created(OffsetDateTime created) {
    this.created = created;
    return this;
  }

  /**
   * Get created
   *
   * @return created
   **/
  @Schema(description = "")
  public OffsetDateTime getCreated() {
    return created;
  }

  public void setCreated(OffsetDateTime created) {
    this.created = created;
  }

  public TrackedTime id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TrackedTime issue(Issue issue) {
    this.issue = issue;
    return this;
  }

  /**
   * Get issue
   *
   * @return issue
   **/
  @Schema(description = "")
  public Issue getIssue() {
    return issue;
  }

  public void setIssue(Issue issue) {
    this.issue = issue;
  }

  public TrackedTime issueId(Long issueId) {
    this.issueId = issueId;
    return this;
  }

  /**
   * deprecated (only for backwards compatibility)
   *
   * @return issueId
   **/
  @Schema(description = "deprecated (only for backwards compatibility)")
  public Long getIssueId() {
    return issueId;
  }

  public void setIssueId(Long issueId) {
    this.issueId = issueId;
  }

  public TrackedTime time(Long time) {
    this.time = time;
    return this;
  }

  /**
   * Time in seconds
   *
   * @return time
   **/
  @Schema(description = "Time in seconds")
  public Long getTime() {
    return time;
  }

  public void setTime(Long time) {
    this.time = time;
  }

  public TrackedTime userId(Long userId) {
    this.userId = userId;
    return this;
  }

  /**
   * deprecated (only for backwards compatibility)
   *
   * @return userId
   **/
  @Schema(description = "deprecated (only for backwards compatibility)")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public TrackedTime userName(String userName) {
    this.userName = userName;
    return this;
  }

  /**
   * Get userName
   *
   * @return userName
   **/
  @Schema(description = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackedTime trackedTime = (TrackedTime) o;
    return Objects.equals(this.created, trackedTime.created) &&
           Objects.equals(this.id, trackedTime.id) &&
           Objects.equals(this.issue, trackedTime.issue) &&
           Objects.equals(this.issueId, trackedTime.issueId) &&
           Objects.equals(this.time, trackedTime.time) &&
           Objects.equals(this.userId, trackedTime.userId) &&
           Objects.equals(this.userName, trackedTime.userName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(created, id, issue, issueId, time, userId, userName);
  }


  @Override
  public String toString() {

    String sb = "class TrackedTime {\n" +
                "    created: " + toIndentedString(created) + "\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    issue: " + toIndentedString(issue) + "\n" +
                "    issueId: " + toIndentedString(issueId) + "\n" +
                "    time: " + toIndentedString(time) + "\n" +
                "    userId: " + toIndentedString(userId) + "\n" +
                "    userName: " + toIndentedString(userName) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
