/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * UpdateBranchProtectionPriories a list to update the branch protection rule priorities
 */
@Schema(description = "UpdateBranchProtectionPriories a list to update the branch protection rule priorities")
public class UpdateBranchProtectionPriories {
  @SerializedName("ids")
  private List<Long> ids;

  public UpdateBranchProtectionPriories ids(List<Long> ids) {
    this.ids = ids;
    return this;
  }

  public UpdateBranchProtectionPriories addIdsItem(Long idsItem) {
    if (this.ids == null) {
      this.ids = new ArrayList<Long>();
    }
    this.ids.add(idsItem);
    return this;
  }

  /**
   * Get ids
   *
   * @return ids
   **/
  @Schema(description = "")
  public List<Long> getIds() {
    return ids;
  }

  public void setIds(List<Long> ids) {
    this.ids = ids;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateBranchProtectionPriories updateBranchProtectionPriories = (UpdateBranchProtectionPriories) o;
    return Objects.equals(this.ids, updateBranchProtectionPriories.ids);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ids);
  }


  @Override
  public String toString() {

    String sb = "class UpdateBranchProtectionPriories {\n" +
                "    ids: " + toIndentedString(ids) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
