/*
 * Gitea API
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.23.0+dev-728-g93640993e3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package dev.mev4.gitea.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * UpdateVariableOption the option when updating variable
 */
@Schema(description = "UpdateVariableOption the option when updating variable")
public class UpdateVariableOption {
  @SerializedName("name")
  private String name;

  @SerializedName("value")
  private String value;

  public UpdateVariableOption name(String name) {
    this.name = name;
    return this;
  }

  /**
   * New name for the variable. If the field is empty, the variable name won&#x27;t be updated.
   *
   * @return name
   **/
  @Schema(description = "New name for the variable. If the field is empty, the variable name won't be updated.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UpdateVariableOption value(String value) {
    this.value = value;
    return this;
  }

  /**
   * Value of the variable to update
   *
   * @return value
   **/
  @Schema(required = true, description = "Value of the variable to update")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateVariableOption updateVariableOption = (UpdateVariableOption) o;
    return Objects.equals(this.name, updateVariableOption.name) &&
           Objects.equals(this.value, updateVariableOption.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, value);
  }


  @Override
  public String toString() {

    String sb = "class UpdateVariableOption {\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    value: " + toIndentedString(value) + "\n" +
                "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
